-- ══════════════════════════════════════════════════════════════════
-- EnglishUp · Giáo trình  (giaotrinh.html)
-- Tạo 3 bảng: curricula → curriculum_units → curriculum_topics
-- Nạp sẵn giáo trình "Oxford PVD — Chủ đề đời sống": 12 nhóm · 128 chủ đề
-- CHẠY LẠI ĐƯỢC NHIỀU LẦN (ON CONFLICT DO UPDATE), không đụng bảng words
-- ══════════════════════════════════════════════════════════════════

create table if not exists curricula (
  code          text primary key,
  title         text not null,
  subtitle      text,
  description   text,
  cover_emoji   text default '📘',
  color         text default '#4f8ef7',
  level_range   text,
  n_units       int  default 0,
  n_topics      int  default 0,
  target_words  int  default 0,
  status        text default 'ready',      -- ready | draft | soon
  ord           int  default 0,
  version       text,
  note          text,
  created_at    timestamptz default now()
);

create table if not exists curriculum_units (
  code             text primary key,
  curriculum_code  text not null references curricula(code) on delete cascade,
  no               int,
  name_en          text,
  name_vi          text,
  note             text,
  n_topics         int,
  target_words     int,
  cefr             text[]
);
create index if not exists idx_cu_curr on curriculum_units(curriculum_code);

create table if not exists curriculum_topics (
  code             text primary key,
  unit_code        text not null references curriculum_units(code) on delete cascade,
  curriculum_code  text not null,
  ord              int,
  name_en          text,
  name_vi          text,
  cefr             text,
  target_words     int,
  objective        text,
  focus            text[],
  pattern          text,
  image_brief      text,
  prompts          text[],
  word_terms       text[],   -- (tuỳ chọn) danh sách từ lấy từ bảng words khi words.topic_code chưa có
  image_url        text
);
create index if not exists idx_ct_unit on curriculum_topics(unit_code);
create index if not exists idx_ct_curr on curriculum_topics(curriculum_code);

-- ── Bổ sung cột nếu bảng đã tồn tại từ lần chạy trước ──────────────
alter table curricula          add column if not exists note text;
alter table curriculum_topics  add column if not exists word_terms text[];
alter table curriculum_topics  add column if not exists image_url text;

-- ── RLS: đọc công khai, ghi bằng anon key (đúng quy ước sẵn có) ────
alter table curricula enable row level security;
drop policy if exists "curricula_all" on curricula;
create policy "curricula_all" on curricula for all using (true) with check (true);
alter table curriculum_units enable row level security;
drop policy if exists "curriculum_units_all" on curriculum_units;
create policy "curriculum_units_all" on curriculum_units for all using (true) with check (true);
alter table curriculum_topics enable row level security;
drop policy if exists "curriculum_topics_all" on curriculum_topics;
create policy "curriculum_topics_all" on curriculum_topics for all using (true) with check (true);

-- ══════════════ 1. DANH MỤC GIÁO TRÌNH ══════════════
insert into curricula ("code","title","subtitle","description","cover_emoji","color","level_range","n_units","n_topics","target_words","status","ord","version","note") values
 ('CDS', 'Oxford PVD — Chủ đề đời sống', 'Từ vựng qua tranh theo 12 nhóm chủ đề đời sống', 'Học từ vựng qua tranh: mỗi chủ đề là một bài học ba bước — học từ, luyện tập trắc nghiệm, rồi trả lời ba câu hỏi mở. Khung định sẵn bậc CEFR, mục tiêu, mẫu câu và gợi ý tranh cho từng chủ đề.', '🖼️', '#4f8ef7', 'A1 – B1', 12, 128, 2817, 'ready', 1, '1.0', 'Dàn ý chủ đề và mô hình sư phạm; toàn bộ mục tiêu, mẫu câu, gợi ý tranh và câu hỏi là nội dung soạn mới.'),
 ('OX3K', 'Oxford 3000 theo cấp độ', 'Lộ trình A1 → B2 bám kho Oxford 3000 sẵn có', 'Đang biên soạn.', '📗', '#34d399', 'A1 – B2', 0, 0, 0, 'soon', 2, NULL, NULL),
 ('PHR150', '150 ngày cụm từ', 'Mỗi ngày một nhóm cụm động từ & giới từ', 'Đang biên soạn.', '🗓️', '#a78bfa', 'A2 – B2', 0, 0, 0, 'soon', 3, NULL, NULL),
 ('WORK', 'Tiếng Anh công việc', 'Email, họp hành, thuyết trình, đàm phán', 'Đang biên soạn.', '💼', '#fb923c', 'B1 – B2', 0, 0, 0, 'soon', 4, NULL, NULL)
on conflict (code) do update set
  "title"=excluded."title",
  "subtitle"=excluded."subtitle",
  "description"=excluded."description",
  "cover_emoji"=excluded."cover_emoji",
  "color"=excluded."color",
  "level_range"=excluded."level_range",
  "n_units"=excluded."n_units",
  "n_topics"=excluded."n_topics",
  "target_words"=excluded."target_words",
  "status"=excluded."status",
  "ord"=excluded."ord",
  "version"=excluded."version",
  "note"=excluded."note";

-- ══════════════ 2. NHÓM CHỦ ĐỀ (12) ══════════════
insert into curriculum_units ("code","curriculum_code","no","name_en","name_vi","note","n_topics","target_words","cefr") values
 ('CDS-U01', 'CDS', 1, 'Everyday Language', 'Ngôn ngữ hằng ngày', 'Nền tảng giao tiếp lớp học và sinh hoạt: hỏi–đáp cơ bản, số, giờ, ngày tháng, màu, giá tiền.', 15, 283, ARRAY['A1','A2']::text[]),
 ('CDS-U02', 'CDS', 2, 'People', 'Con người', 'Nói về bản thân và gia đình: ngoại hình, quan hệ, thói quen, cảm xúc, cột mốc cuộc đời.', 7, 142, ARRAY['A1','A2','B1']::text[]),
 ('CDS-U03', 'CDS', 3, 'Housing', 'Nhà ở', 'Chỗ ở và mọi thứ trong nhà: tìm nhà, từng phòng, việc nhà, hỏng hóc và sửa chữa.', 14, 290, ARRAY['A1','A2','B1']::text[]),
 ('CDS-U04', 'CDS', 4, 'Food', 'Ăn uống', 'Ăn uống trọn vòng: thực phẩm tươi, đi chợ và siêu thị, nấu nướng, ăn tiệm và gọi món.', 12, 270, ARRAY['A1','A2','B1']::text[]),
 ('CDS-U05', 'CDS', 5, 'Clothing', 'Quần áo', 'Quần áo và phụ kiện: gọi tên, mô tả, mua sắm, giặt là, sửa đồ.', 7, 158, ARRAY['A1','A2','B1']::text[]),
 ('CDS-U06', 'CDS', 6, 'Health', 'Sức khỏe', 'Cơ thể và chăm sóc sức khỏe: mô tả triệu chứng, đi khám, nhà thuốc, cấp cứu — mức từ vựng đời thường.', 10, 240, ARRAY['A1','A2','B1']::text[]),
 ('CDS-U07', 'CDS', 7, 'Community', 'Cộng đồng', 'Ra khỏi nhà: phố xá, cửa hàng, ngân hàng, thư viện, dịch vụ công và an toàn.', 11, 254, ARRAY['A2','B1']::text[]),
 ('CDS-U08', 'CDS', 8, 'Transportation', 'Đi lại', 'Di chuyển: xe cộ, giao thông công cộng, chỉ đường, biển báo, sân bay và chuyến bay.', 7, 160, ARRAY['A1','A2','B1']::text[]),
 ('CDS-U09', 'CDS', 9, 'Areas of Study', 'Môn học', 'Ngôn ngữ học đường: các môn học, viết luận, địa lý, khoa học, môi trường, vũ trụ.', 13, 312, ARRAY['A2','B1']::text[]),
 ('CDS-U10', 'CDS', 10, 'Plants and Animals', 'Cây cỏ & muông thú', 'Thế giới tự nhiên: cây cỏ, hoa, sinh vật biển, chim, côn trùng, thú nuôi và thú hoang.', 6, 134, ARRAY['A1','A2']::text[]),
 ('CDS-U11', 'CDS', 11, 'Work', 'Công việc', 'Đi làm: nghề nghiệp, kỹ năng, xin việc, văn phòng, nhà máy, công trường, an toàn lao động.', 12, 274, ARRAY['A1','A2','B1']::text[]),
 ('CDS-U12', 'CDS', 12, 'Recreation', 'Giải trí', 'Thời gian rảnh: đi chơi, thể thao, sở thích, thiết bị, giải trí, ngày lễ và tiệc tùng.', 14, 300, ARRAY['A1','A2','B1']::text[])
on conflict (code) do update set
  "curriculum_code"=excluded."curriculum_code",
  "no"=excluded."no",
  "name_en"=excluded."name_en",
  "name_vi"=excluded."name_vi",
  "note"=excluded."note",
  "n_topics"=excluded."n_topics",
  "target_words"=excluded."target_words",
  "cefr"=excluded."cefr";

-- ══════════════ 3. CHỦ ĐỀ (128) ══════════════
insert into curriculum_topics ("code","unit_code","curriculum_code","ord","name_en","name_vi","cefr","target_words","objective","focus","pattern","image_brief","prompts") values
 ('CDS-U01-01', 'CDS-U01', 'CDS', 1, 'A Classroom', 'Lớp học', 'A1', 20, 'Gọi tên được đồ vật trong lớp học và nói vị trí của chúng bằng câu đơn giản.', ARRAY['danh từ chỉ đồ vật','giới từ chỉ vị trí']::text[], 'Where is the …? — It''s on the …', 'Một lớp học Việt Nam nhìn từ cuối phòng: bảng, bàn ghế, cặp sách, quạt trần, đồng hồ treo tường.', ARRAY['What is in your classroom?','Where do you sit in class?','What do you bring to class every day?']::text[]),
 ('CDS-U01-02', 'CDS-U01', 'CDS', 2, 'Personal Information', 'Thông tin cá nhân', 'A1', 16, 'Cung cấp được thông tin cá nhân cơ bản và điền một tờ khai đơn giản.', ARRAY['danh từ chỉ thông tin cá nhân','số']::text[], 'What''s your …? — My … is …', 'Cận cảnh tờ khai thông tin có ô họ tên, ngày sinh, địa chỉ, số điện thoại, kèm thẻ căn cước đặt bên cạnh.', ARRAY['What is your full name?','Where do you live?','When is your birthday?']::text[]),
 ('CDS-U01-03', 'CDS-U01', 'CDS', 3, 'School', 'Trường học', 'A1', 18, 'Gọi tên được các khu vực và những người làm việc trong trường học.', ARRAY['danh từ chỉ nơi chốn','danh từ chỉ người']::text[], 'Where is the …? — It''s next to the …', 'Toàn cảnh sân trường Việt Nam giờ ra chơi: dãy lớp học, thư viện, phòng y tế, căng tin, cột cờ.', ARRAY['What is your school like?','Where do you eat lunch at school?','Who do you talk to at school?']::text[]),
 ('CDS-U01-04', 'CDS-U01', 'CDS', 4, 'Studying', 'Việc học tập', 'A2', 22, 'Mô tả được các hoạt động học tập trên lớp và ở nhà theo trình tự.', ARRAY['động từ chỉ hoạt động học','cụm động từ trong lớp']::text[], 'First I …, then I …', 'Bộ tranh nhỏ mô tả các bước học: đọc bài, gạch chân từ mới, tra từ điển, làm bài nhóm, lên bảng trình bày.', ARRAY['How do you learn new English words?','When and where do you usually study?','What makes studying difficult for you?']::text[]),
 ('CDS-U01-05', 'CDS-U01', 'CDS', 5, 'Everyday Conversation', 'Giao tiếp hằng ngày', 'A2', 20, 'Mở đầu, duy trì và kết thúc được một cuộc trò chuyện ngắn hằng ngày.', ARRAY['cụm chào hỏi','động từ giao tiếp']::text[], 'Excuse me, could you …? — Sure, no problem.', 'Bộ tranh tình huống trò chuyện ngắn: chào hàng xóm, hỏi đường, xin lỗi khi va phải người khác, giới thiệu bạn mới.', ARRAY['How do you greet people in Vietnam?','What do you say when you meet someone new?','When was the last time you talked to a stranger?']::text[]),
 ('CDS-U01-06', 'CDS-U01', 'CDS', 6, 'The Telephone', 'Điện thoại', 'A2', 20, 'Thực hiện được một cuộc gọi đơn giản, để lại và nhận lời nhắn.', ARRAY['danh từ chỉ thiết bị','động từ chỉ thao tác gọi điện']::text[], 'Hello, may I speak to …? — Sorry, he''s not here.', 'Cận cảnh màn hình điện thoại di động đang gọi, bên cạnh là tai nghe, sim, cục sạc và danh sách cuộc gọi nhỡ.', ARRAY['Who do you call the most?','What do you use your phone for every day?','Do you prefer calling or texting? Why?']::text[]),
 ('CDS-U01-07', 'CDS-U01', 'CDS', 7, 'Weather', 'Thời tiết', 'A1', 18, 'Nói được thời tiết hôm nay và cảm giác nóng lạnh của mình.', ARRAY['tính từ chỉ thời tiết','danh từ chỉ hiện tượng tự nhiên']::text[], 'What''s the weather like? — It''s hot and rainy.', 'Bộ tranh bốn ô thời tiết Việt Nam: nắng gắt, mưa rào, trời nhiều mây, gió bão ven biển.', ARRAY['What''s the weather like today?','Do you like rain?','What is your favorite season?']::text[]),
 ('CDS-U01-08', 'CDS-U01', 'CDS', 8, 'Describing Things', 'Mô tả đồ vật', 'A2', 20, 'Mô tả được đồ vật theo kích thước, hình dạng, chất liệu và tình trạng.', ARRAY['tính từ chỉ kích thước','tính từ chỉ chất liệu']::text[], 'It''s a small, round, wooden box.', 'Bàn bày các vật đối lập nhau: hộp to và nhỏ, cốc thủy tinh và cốc nhựa, khăn mới và cũ, quả bóng tròn cạnh hộp vuông.', ARRAY['Describe something you use every day.','What is your favorite thing at home, and why?','Do you prefer new things or old things?']::text[]),
 ('CDS-U01-09', 'CDS-U01', 'CDS', 9, 'Colors', 'Màu sắc', 'A1', 14, 'Gọi tên được các màu cơ bản và nói màu của đồ vật quanh mình.', ARRAY['tính từ chỉ màu sắc']::text[], 'What color is it? — It''s blue.', 'Bảng màu tròn với các ô màu cơ bản, kèm đồ vật đời thường đúng màu: áo đỏ, xe xanh, mũ vàng.', ARRAY['What is your favorite color?','What color is your bag?','What colors do you like to wear?']::text[]),
 ('CDS-U01-10', 'CDS-U01', 'CDS', 10, 'Prepositions', 'Giới từ chỉ vị trí', 'A1', 15, 'Nói được vị trí của người và đồ vật bằng giới từ chỉ nơi chốn.', ARRAY['giới từ chỉ vị trí']::text[], 'The cat is under the table.', 'Một chú mèo ở nhiều vị trí quanh chiếc bàn: trên, dưới, sau, trước, bên cạnh và giữa hai chiếc ghế.', ARRAY['Where is your phone now?','What is next to your bed?','Where do you keep your keys?']::text[]),
 ('CDS-U01-11', 'CDS-U01', 'CDS', 11, 'Numbers and Measurements', 'Số đếm và đo lường', 'A2', 22, 'Đọc và dùng được số đếm, số thứ tự cùng các đơn vị đo thông dụng.', ARRAY['số đếm và số thứ tự','danh từ chỉ đơn vị đo']::text[], 'How tall are you? — I''m one meter sixty.', 'Bộ dụng cụ đo: thước dây, cân sức khỏe, ca đong, nhiệt kế, kèm bảng số từ 1 đến 100.', ARRAY['How far is your home from here?','How much do you spend on lunch each day?','When do you use numbers at work or school?']::text[]),
 ('CDS-U01-12', 'CDS-U01', 'CDS', 12, 'Time', 'Giờ giấc', 'A1', 18, 'Hỏi và nói được giờ cùng các buổi trong ngày.', ARRAY['danh từ chỉ thời gian','cụm chỉ giờ']::text[], 'What time is it? — It''s half past seven.', 'Đồng hồ kim chỉ nhiều mốc giờ khác nhau, kèm tranh buổi sáng, trưa, chiều và tối của một ngày.', ARRAY['What time do you get up?','What time do you go to bed?','When do you eat lunch?']::text[]),
 ('CDS-U01-13', 'CDS-U01', 'CDS', 13, 'The Calendar', 'Lịch và ngày tháng', 'A1', 18, 'Nói được thứ, ngày, tháng và các dịp quan trọng trong năm.', ARRAY['danh từ chỉ thứ và tháng','số thứ tự chỉ ngày']::text[], 'What day is it today? — It''s Monday, May 5th.', 'Tờ lịch tháng treo tường có khoanh tròn ngày lễ, kèm lịch bàn ghi chú sinh nhật và ngày nghỉ.', ARRAY['What day is it today?','What do you do on Sunday?','When is Tet in your family?']::text[]),
 ('CDS-U01-14', 'CDS-U01', 'CDS', 14, 'Money', 'Tiền bạc', 'A2', 20, 'Nói về giá cả, cách thanh toán và các thao tác tiền bạc thường ngày.', ARRAY['danh từ chỉ tiền','động từ chỉ giao dịch']::text[], 'How much is it? — It''s fifty thousand dong.', 'Quầy thu ngân với tiền giấy, tiền xu, thẻ ngân hàng, mã QR thanh toán và hóa đơn in.', ARRAY['How do you usually pay: cash, card, or QR code?','Do you save money every month? How?','What did you buy last week?']::text[]),
 ('CDS-U01-15', 'CDS-U01', 'CDS', 15, 'Shopping', 'Mua sắm', 'A2', 22, 'Thực hiện được một giao dịch mua hàng: hỏi giá, mặc cả, đổi trả và lấy hóa đơn.', ARRAY['danh từ chỉ nơi mua sắm','động từ chỉ mua bán']::text[], 'Can I return this? — Do you have the receipt?', 'Cảnh siêu thị và chợ truyền thống Việt Nam: giỏ hàng, biển giảm giá, quầy tính tiền, người bán trả lại tiền thừa.', ARRAY['Where do you like to shop: markets or supermarkets?','What do you do if something is too expensive?','Tell me about the last thing you bought online.']::text[]),
 ('CDS-U02-01', 'CDS-U02', 'CDS', 1, 'Age and Physical Description', 'Tuổi tác và ngoại hình', 'A2', 20, 'Mô tả được tuổi, chiều cao, vóc dáng và ngoại hình của một người.', ARRAY['tính từ chỉ ngoại hình','danh từ chỉ độ tuổi']::text[], 'What does he look like? — He''s tall and thin.', 'Hàng người đủ lứa tuổi và vóc dáng đứng cạnh nhau: em bé, thiếu niên, người trung niên, người già, cao thấp mập gầy.', ARRAY['Who in your family do you look like?','How would you describe your best friend?','Do people think you look young for your age?']::text[]),
 ('CDS-U02-02', 'CDS-U02', 'CDS', 2, 'Describing Hair', 'Mô tả mái tóc', 'A2', 16, 'Mô tả được kiểu tóc, màu tóc và nói được yêu cầu khi đi cắt tóc.', ARRAY['tính từ chỉ kiểu tóc','danh từ chỉ dịch vụ làm tóc']::text[], 'She has long, straight, black hair.', 'Bảng mẫu tóc trong tiệm làm tóc: tóc dài thẳng, tóc xoăn, tóc ngắn, buộc đuôi ngựa, tóc nhuộm, đầu hói.', ARRAY['How would you describe your hair?','How often do you go to the hairdresser?','Have you ever changed your hairstyle?']::text[]),
 ('CDS-U02-03', 'CDS-U02', 'CDS', 3, 'Family', 'Gia đình', 'A1', 20, 'Giới thiệu được các thành viên trong gia đình và quan hệ họ hàng cơ bản.', ARRAY['danh từ chỉ quan hệ gia đình']::text[], 'This is my sister. She is a nurse.', 'Ảnh gia đình ba thế hệ Việt Nam quanh bàn ăn, có ông bà, cha mẹ, con cháu, kèm sơ đồ cây phả hệ nhỏ bên cạnh.', ARRAY['How many people are in your family?','Who do you live with?','Do you have a brother or a sister?']::text[]),
 ('CDS-U02-04', 'CDS-U02', 'CDS', 4, 'Daily Routines', 'Sinh hoạt hằng ngày', 'A2', 22, 'Kể lại được một ngày bình thường của mình theo trình tự thời gian.', ARRAY['động từ chỉ thói quen','trạng từ chỉ tần suất']::text[], 'I usually get up at six and go to work at seven.', 'Dải tranh một ngày: thức dậy, đánh răng, ăn sáng, chạy xe máy đi làm, ăn tối, xem tivi, đi ngủ.', ARRAY['What do you do every morning?','What is the busiest part of your day?','Is your weekend different from your weekdays?']::text[]),
 ('CDS-U02-05', 'CDS-U02', 'CDS', 5, 'Life Events', 'Các mốc trong đời', 'B1', 24, 'Kể lại được những sự kiện quan trọng trong đời một người và giấy tờ đi kèm.', ARRAY['danh từ chỉ sự kiện đời người','động từ ở thì quá khứ']::text[], 'He graduated in 2015 and got married two years later.', 'Chuỗi ảnh đời người: chào đời, đi học, tốt nghiệp, đám cưới, chuyển nhà, nghỉ hưu, kèm giấy khai sinh và bằng tốt nghiệp.', ARRAY['What has been the most important event in your life so far?','How do families in Vietnam usually celebrate a wedding?','What would you like to achieve in the next five years?']::text[]),
 ('CDS-U02-06', 'CDS-U02', 'CDS', 6, 'Feelings', 'Cảm xúc', 'A2', 20, 'Nói được cảm xúc của mình kèm lý do và hỏi cảm xúc của người khác.', ARRAY['tính từ chỉ cảm xúc','động từ chỉ trạng thái']::text[], 'How do you feel? — I feel tired because I slept late.', 'Bộ khuôn mặt biểu cảm: vui, buồn, giận, lo lắng, mệt, ngạc nhiên, xấu hổ, phấn khích.', ARRAY['How do you feel today, and why?','What makes you happy after a long day?','What do you do when you feel stressed?']::text[]),
 ('CDS-U02-07', 'CDS-U02', 'CDS', 7, 'A Graduation', 'Lễ tốt nghiệp', 'A2', 20, 'Mô tả được một buổi lễ tốt nghiệp và các hoạt động chúc mừng đi kèm.', ARRAY['danh từ chỉ buổi lễ','động từ chỉ hoạt động trong lễ']::text[], 'They took photos after the ceremony.', 'Sân trường ngày tốt nghiệp: áo cử nhân, mũ tua, tấm bằng, bó hoa, gia đình chụp ảnh, sân khấu phát biểu.', ARRAY['Have you ever been to a graduation ceremony?','Who do you invite to an important ceremony?','How do people celebrate finishing school in your hometown?']::text[]),
 ('CDS-U03-01', 'CDS-U03', 'CDS', 1, 'Places to Live', 'Các kiểu nơi ở', 'A1', 16, 'Gọi tên được các kiểu nơi ở và nói mình đang sống ở đâu.', ARRAY['danh từ chỉ kiểu nhà ở']::text[], 'I live in an apartment in the city.', 'Bộ tranh các kiểu nơi ở: nhà phố, chung cư, nhà cấp bốn ở quê, ký túc xá, phòng trọ, nhà sàn.', ARRAY['Where do you live?','Do you live in a city or in the countryside?','Is your home big or small?']::text[]),
 ('CDS-U03-02', 'CDS-U03', 'CDS', 2, 'Finding a Home', 'Tìm nhà ở', 'B1', 26, 'Trình bày được các bước tìm và thuê nhà, hiểu tin rao cùng hợp đồng cơ bản.', ARRAY['danh từ chỉ thủ tục thuê nhà','động từ chỉ quy trình']::text[], 'How much is the deposit? — It''s one month''s rent.', 'Người xem nhà cùng môi giới: tin rao dán tường, chùm chìa khóa, hợp đồng thuê, tiền cọc, xe tải chuyển nhà.', ARRAY['What do you look for when you rent a place?','What problems can happen between landlords and tenants?','Is it better to rent or to buy a home in Vietnam? Why?']::text[]),
 ('CDS-U03-03', 'CDS-U03', 'CDS', 3, 'Apartments', 'Chung cư', 'A2', 24, 'Mô tả được các khu vực trong tòa chung cư và cách dùng tiện ích chung.', ARRAY['danh từ chỉ khu vực trong tòa nhà','động từ chỉ việc sử dụng tiện ích']::text[], 'The gym is on the second floor.', 'Mặt cắt một tòa chung cư: sảnh, thang máy, hầm để xe, hộp thư, ban công, sân chơi, bảo vệ ở cổng.', ARRAY['What do you like about living in an apartment building?','Which shared spaces do you use most?','How do you get along with your neighbors?']::text[]),
 ('CDS-U03-04', 'CDS-U03', 'CDS', 4, 'A House', 'Ngôi nhà', 'A1', 20, 'Gọi tên được các phòng và bộ phận bên ngoài của một ngôi nhà.', ARRAY['danh từ chỉ phòng','danh từ chỉ bộ phận ngôi nhà']::text[], 'How many rooms are there? — There are four.', 'Ngôi nhà Việt Nam nhìn từ ngoài và mặt cắt bên trong: mái, cửa chính, cửa sổ, cầu thang, các phòng.', ARRAY['How many rooms are in your house?','Which room do you like best?','Do you have a balcony?']::text[]),
 ('CDS-U03-05', 'CDS-U03', 'CDS', 5, 'A Yard', 'Sân vườn', 'A1', 18, 'Gọi tên được đồ vật và cây cối ngoài sân vườn quanh nhà.', ARRAY['danh từ chỉ đồ vật ngoài trời','danh từ chỉ cây cối']::text[], 'There is a tree in the yard.', 'Sân trước một ngôi nhà ở quê: hàng rào, giàn hoa giấy, chậu cây, vòi nước, xe máy dựng góc sân, chó nằm ở hiên.', ARRAY['Do you have a yard or a garden?','What plants do you like?','Where do you sit outside at home?']::text[]),
 ('CDS-U03-06', 'CDS-U03', 'CDS', 6, 'A Kitchen', 'Nhà bếp', 'A1', 22, 'Gọi tên được đồ dùng, thiết bị trong bếp và nói vị trí của chúng.', ARRAY['danh từ chỉ thiết bị bếp','giới từ chỉ vị trí']::text[], 'The rice cooker is on the counter.', 'Gian bếp gia đình Việt: bếp gas, nồi cơm điện, tủ lạnh, bồn rửa, chạn bát, hũ gia vị, máy hút mùi.', ARRAY['What is in your kitchen?','Who cooks in your family?','What do you cook most often?']::text[]),
 ('CDS-U03-07', 'CDS-U03', 'CDS', 7, 'A Dining Area', 'Khu vực ăn uống', 'A1', 18, 'Gọi tên được đồ dùng trên bàn ăn và nói cách bày mâm cơm.', ARRAY['danh từ chỉ đồ dùng ăn uống']::text[], 'Please pass me the bowl.', 'Bàn ăn dọn sẵn kiểu Việt: mâm cơm, bát đũa, thìa, đĩa, cốc nước, khăn giấy, nồi canh đặt giữa bàn.', ARRAY['Where does your family eat dinner?','What is on your table at dinner?','Do you eat with your family every day?']::text[]),
 ('CDS-U03-08', 'CDS-U03', 'CDS', 8, 'A Living Room', 'Phòng khách', 'A1', 20, 'Gọi tên được đồ đạc trong phòng khách và nói cách sắp xếp chúng.', ARRAY['danh từ chỉ đồ nội thất','giới từ chỉ vị trí']::text[], 'The sofa is in front of the TV.', 'Phòng khách gia đình: bộ sofa, bàn trà, tivi, tủ thờ, quạt cây, tranh treo tường, cửa sổ có rèm.', ARRAY['What is in your living room?','What do you do in your living room?','Where do guests sit in your home?']::text[]),
 ('CDS-U03-09', 'CDS-U03', 'CDS', 9, 'A Bathroom', 'Phòng tắm', 'A1', 20, 'Gọi tên được thiết bị và đồ dùng trong phòng tắm.', ARRAY['danh từ chỉ thiết bị vệ sinh','danh từ chỉ đồ dùng cá nhân']::text[], 'Where is the towel? — It''s on the hook.', 'Phòng tắm nhỏ gọn: bồn rửa mặt, gương, vòi sen, bồn cầu, máy nước nóng, giá treo khăn, xô nhựa.', ARRAY['What do you do first in the bathroom every morning?','Is your bathroom big or small?','What things do you keep in your bathroom?']::text[]),
 ('CDS-U03-10', 'CDS-U03', 'CDS', 10, 'A Bedroom', 'Phòng ngủ', 'A1', 20, 'Gọi tên được đồ đạc trong phòng ngủ và mô tả chỗ ngủ của mình.', ARRAY['danh từ chỉ đồ dùng phòng ngủ','tính từ mô tả']::text[], 'My bed is next to the window.', 'Phòng ngủ đơn giản: giường, chăn gối, màn, tủ quần áo, bàn nhỏ, đèn ngủ, điều hòa và quạt.', ARRAY['What is in your bedroom?','What time do you sleep?','Do you share your bedroom?']::text[]),
 ('CDS-U03-11', 'CDS-U03', 'CDS', 11, 'A Children''s Bedroom', 'Phòng của trẻ', 'A1', 20, 'Gọi tên được đồ dùng và đồ chơi trong phòng của trẻ nhỏ.', ARRAY['danh từ chỉ đồ dùng trẻ em','danh từ chỉ đồ chơi']::text[], 'The toys are in the box.', 'Phòng trẻ em nhiều màu: giường tầng, nôi, thảm chơi, hộp đồ chơi, gấu bông, bàn học nhỏ, tranh dán tường.', ARRAY['What toys did you like as a child?','Where do children play in your home?','Is a child''s room easy to keep clean?']::text[]),
 ('CDS-U03-12', 'CDS-U03', 'CDS', 12, 'Housework', 'Việc nhà', 'A2', 22, 'Nói về các việc nhà hằng ngày và cách chia việc giữa các thành viên.', ARRAY['động từ chỉ việc nhà','trạng từ chỉ tần suất']::text[], 'I do the dishes every night.', 'Bộ tranh việc nhà: quét nhà, lau sàn, rửa bát, phơi quần áo, gấp đồ, đổ rác, tưới cây.', ARRAY['Which housework do you do at home?','Who does the most housework in your family?','Which chore do you dislike the most, and why?']::text[]),
 ('CDS-U03-13', 'CDS-U03', 'CDS', 13, 'Cleaning Supplies', 'Đồ dùng vệ sinh', 'A1', 18, 'Gọi tên được các dụng cụ và chất tẩy rửa dùng để dọn dẹp nhà cửa.', ARRAY['danh từ chỉ dụng cụ dọn dẹp']::text[], 'I need a mop and a bucket.', 'Góc để đồ dọn dẹp: chổi, cây lau nhà, xô, giẻ lau, nước rửa chén, nước lau sàn, găng tay, túi rác.', ARRAY['What do you use to clean the floor?','When do you clean your home?','What cleaning things do you buy every month?']::text[]),
 ('CDS-U03-14', 'CDS-U03', 'CDS', 14, 'Household Problems and Repairs', 'Hỏng hóc và sửa chữa trong nhà', 'B1', 26, 'Trình bày được sự cố trong nhà và gọi đúng thợ sửa chữa phù hợp.', ARRAY['danh từ chỉ sự cố nhà cửa','danh từ chỉ thợ sửa chữa']::text[], 'The sink is leaking. Could you send someone to fix it?', 'Các sự cố trong nhà: vòi nước rò rỉ, tường thấm nước, mất điện, khóa cửa hỏng, mối mọt, kèm thợ điện và thợ nước đang sửa.', ARRAY['What was the last thing that broke in your home?','Do you fix things yourself or call someone?','How do you find a reliable repair person in your area?']::text[]),
 ('CDS-U04-01', 'CDS-U04', 'CDS', 1, 'Fruit', 'Trái cây', 'A1', 22, 'Gọi tên được các loại trái cây quen thuộc và hỏi mua theo cân ở chợ.', ARRAY['danh từ đếm được','danh từ không đếm được']::text[], 'I''d like a kilo of …, please.', 'Sạp trái cây ngoài chợ Việt bày xoài, chuối, ổi, thanh long, dưa hấu, nho, cam, kèm cân đồng hồ treo bên trên.', ARRAY['What fruit do you eat every week?','Which fruit is cheap in your city now?','Do you like sweet fruit or sour fruit?']::text[]),
 ('CDS-U04-02', 'CDS-U04', 'CDS', 2, 'Vegetables', 'Rau củ', 'A1', 24, 'Gọi tên được rau củ thường dùng và nói mình mua bao nhiêu cho bữa ăn gia đình.', ARRAY['danh từ chỉ thực phẩm','lượng từ']::text[], 'I need some … and two …', 'Bàn bếp bày rau củ tươi: rau muống, cải xanh, cà rốt, khoai tây, cà chua, hành lá, bí đỏ, nấm, sắp thành từng bó.', ARRAY['What vegetables do you buy the most?','Is there a vegetable you never eat? Why?','Who cooks the vegetables in your home?']::text[]),
 ('CDS-U04-03', 'CDS-U04', 'CDS', 3, 'Meat and Poultry', 'Thịt và gia cầm', 'A1', 20, 'Gọi tên được các loại thịt, phần thịt và hỏi giá tại quầy thịt.', ARRAY['danh từ không đếm được','tính từ chỉ trạng thái']::text[], 'How much is a kilo of …?', 'Quầy thịt trong siêu thị: thịt heo, thịt bò, sườn, ức gà, đùi gà, trứng, có bảng giá cắm trên khay.', ARRAY['What meat do you eat most often?','How often does your family eat chicken?','Do you buy meat at a market or a supermarket?']::text[]),
 ('CDS-U04-04', 'CDS-U04', 'CDS', 4, 'Deli and Seafood', 'Đồ nguội và hải sản', 'A2', 22, 'Đặt mua đồ nguội và hải sản theo số lượng, đồng thời hỏi về độ tươi của hàng.', ARRAY['danh từ chỉ thực phẩm','tính từ mô tả']::text[], 'Half a kilo of …, and is it fresh today?', 'Tủ kính quầy hải sản với tôm, mực, cá thu, nghêu trên đá lạnh, bên cạnh là quầy đồ nguội cắt lát: giăm bông, xúc xích, phô mai.', ARRAY['What seafood is popular where you grew up?','How can you tell if fish is fresh?','When was the last time you ate seafood with friends?']::text[]),
 ('CDS-U04-05', 'CDS-U04', 'CDS', 5, 'The Market', 'Đi siêu thị', 'A2', 24, 'Hỏi đường đến đúng khu hàng trong siêu thị và hoàn tất việc thanh toán ở quầy thu ngân.', ARRAY['danh từ chỉ khu vực','động từ mua bán']::text[], 'Excuse me, which aisle is the … in?', 'Toàn cảnh bên trong siêu thị: các dãy kệ có bảng tên, xe đẩy, giỏ hàng, quầy thu ngân với khách xếp hàng.', ARRAY['How often do you go to the supermarket?','What do you always put in your cart?','Do you make a shopping list before you go? Why or why not?']::text[]),
 ('CDS-U04-06', 'CDS-U04', 'CDS', 6, 'Containers and Packaged Foods', 'Bao bì thực phẩm', 'A2', 24, 'Mô tả được thực phẩm theo loại bao bì và yêu cầu đúng số lượng khi mua.', ARRAY['danh từ chỉ vật chứa','cụm định lượng']::text[], 'Can I have two bottles of … and a jar of …?', 'Kệ hàng đóng gói: chai nước mắm, lon nước ngọt, hộp sữa giấy, hũ mứt, túi gạo, gói mì, thùng bia xếp chồng.', ARRAY['What packaged food is always in your kitchen?','Do you read the label before you buy something?','What do you do with empty bottles and boxes at home?']::text[]),
 ('CDS-U04-07', 'CDS-U04', 'CDS', 7, 'Weights and Measures', 'Cân đo định lượng', 'A2', 18, 'Dùng đúng đơn vị cân và đong để nói lượng nguyên liệu khi mua hoặc khi nấu.', ARRAY['danh từ chỉ đơn vị đo','số đếm']::text[], 'It''s about 300 grams — a little more than …', 'Bàn bếp với cân điện tử hiện số gram, cốc đong có vạch, thìa đong, chai một lít nước đặt cạnh túi đường.', ARRAY['Do you measure ingredients when you cook, or guess?','How much rice does your family cook each day?','Which is easier for you: grams or cups? Why?']::text[]),
 ('CDS-U04-08', 'CDS-U04', 'CDS', 8, 'Food Preparation', 'Sơ chế và nấu ăn', 'A2', 26, 'Kể lại từng bước nấu một món đơn giản bằng các động từ chế biến theo đúng thứ tự.', ARRAY['động từ chỉ hành động bếp núc','trạng từ chỉ thứ tự']::text[], 'First wash the …, then chop it and fry it.', 'Bộ tranh sáu ô liền mạch: rửa rau, thái hành, trộn gia vị, chiên trứng, luộc mì, bày ra đĩa.', ARRAY['What is the first dish you learned to cook?','Explain how you make your favorite breakfast.','Do you prefer boiled food or fried food? Why?']::text[]),
 ('CDS-U04-09', 'CDS-U04', 'CDS', 9, 'Kitchen Utensils', 'Dụng cụ nhà bếp', 'A1', 22, 'Gọi tên được dụng cụ nhà bếp và nhờ người khác đưa đúng dụng cụ mình cần.', ARRAY['danh từ chỉ đồ vật','động từ yêu cầu']::text[], 'Can you pass me the …, please?', 'Góc bếp gia đình treo và bày muôi, vá, chảo, nồi, dao, thớt, rổ, đũa cả, nồi cơm điện.', ARRAY['What do you use every time you cook?','Which kitchen tool do you never use?','Who washes the pots and pans in your house?']::text[]),
 ('CDS-U04-10', 'CDS-U04', 'CDS', 10, 'Fast Food', 'Đồ ăn nhanh', 'A1', 20, 'Gọi món ăn nhanh tại quầy và chọn ăn tại chỗ hay mang về.', ARRAY['danh từ chỉ món ăn','động từ gọi món']::text[], 'One … and a small …, to go.', 'Quầy gọi món của tiệm ăn nhanh: bảng thực đơn có hình, khay đựng burger, khoai chiên, gà rán, nước ngọt ly giấy.', ARRAY['How often do you eat fast food?','What do you usually order?','Do you eat there or take the food home?']::text[]),
 ('CDS-U04-11', 'CDS-U04', 'CDS', 11, 'A Coffee Shop Menu', 'Thực đơn quán cà phê', 'A2', 22, 'Đọc hiểu thực đơn quán cà phê và gọi đồ uống kèm yêu cầu riêng về đá, đường, cỡ ly.', ARRAY['danh từ chỉ đồ uống','tính từ chỉ kích cỡ']::text[], 'A large … with less sugar, please.', 'Bảng thực đơn treo tường quán cà phê Việt: cà phê sữa đá, trà đào, sinh tố, bánh ngọt, kèm cỡ ly và giá.', ARRAY['What do you usually order at a coffee shop?','Do you go to coffee shops to work, or to meet people?','Describe a coffee shop you like and why you like it.']::text[]),
 ('CDS-U04-12', 'CDS-U04', 'CDS', 12, 'A Restaurant', 'Nhà hàng', 'B1', 26, 'Xử lý được toàn bộ quy trình ăn nhà hàng, từ đặt bàn, gọi món, đổi món đến hỏi hóa đơn.', ARRAY['danh từ chỉ nghề nghiệp và khu vực','động từ giao tiếp lịch sự']::text[], 'Could we have a table for four, and could you bring the bill later?', 'Bộ tranh bốn ô: khách đặt bàn ở quầy lễ tân, phục vụ ghi món, món ăn được bưng ra, khách thanh toán hóa đơn.', ARRAY['Describe the best meal you have had in a restaurant.','What would you do if the food arrived cold or wrong?','How is eating out in Vietnam different from what you have seen abroad or in films?']::text[]),
 ('CDS-U05-01', 'CDS-U05', 'CDS', 1, 'Clothing I', 'Quần áo mặc hằng ngày', 'A1', 22, 'Gọi tên được quần áo mặc thường ngày và nói mình đang mặc gì hôm nay.', ARRAY['danh từ chỉ trang phục','động từ chỉ hành động mặc']::text[], 'I''m wearing a … and …', 'Bốn người đứng cạnh nhau trong trang phục thường ngày: áo thun, sơ mi, quần jean, váy, quần short, áo khoác mỏng.', ARRAY['What are you wearing today?','What clothes do you wear to work or school?','Where do you buy most of your clothes?']::text[]),
 ('CDS-U05-02', 'CDS-U05', 'CDS', 2, 'Clothing II', 'Đồ mùa lạnh và đồ ngủ', 'A1', 20, 'Chọn và gọi tên được đồ mặc khi trời lạnh, trời mưa và đồ mặc ở nhà lúc đi ngủ.', ARRAY['danh từ chỉ trang phục','tính từ chỉ thời tiết']::text[], 'When it''s cold, I put on my …', 'Hai cảnh đối nhau: bên trái người mặc áo len, áo phao, khăn quàng, mũ len, áo mưa; bên phải người mặc đồ bộ ngủ, áo choàng tắm, dép trong nhà.', ARRAY['What do you wear when the weather is cold?','What do you wear at home in the evening?','Do you have a favorite warm jacket? Describe it.']::text[]),
 ('CDS-U05-03', 'CDS-U05', 'CDS', 3, 'Clothing III', 'Đồ lót và đồ thể thao', 'A2', 20, 'Nói được về đồ lót, đồ tập và chọn trang phục phù hợp cho từng môn vận động.', ARRAY['danh từ chỉ trang phục','cụm động từ chỉ mục đích']::text[], 'For running, I usually wear …', 'Kệ cửa hàng đồ thể thao: áo tập, quần legging, quần đùi thể thao, áo bra thể thao, tất thể thao, bên cạnh ngăn tủ đồ lót gấp gọn.', ARRAY['What do you wear when you exercise?','Which sports clothes are the most comfortable for you?','Do you buy sports clothes online or in a shop? Why?']::text[]),
 ('CDS-U05-04', 'CDS-U05', 'CDS', 4, 'Shoes and Accessories', 'Giày dép và phụ kiện', 'A1', 24, 'Gọi tên giày dép, phụ kiện và hỏi đúng cỡ, đúng màu khi thử đồ trong cửa hàng.', ARRAY['danh từ chỉ đồ vật','tính từ chỉ màu sắc và cỡ']::text[], 'Do you have these in size …?', 'Cửa hàng giày dép và phụ kiện: giày thể thao, dép, giày cao gót, xăng đan trên kệ; tủ kính bày túi xách, thắt lưng, kính râm, đồng hồ, mũ.', ARRAY['How many pairs of shoes do you have?','What accessory do you wear every day?','What shoes do you wear when it rains?']::text[]),
 ('CDS-U05-05', 'CDS-U05', 'CDS', 5, 'Describing Clothes', 'Mô tả quần áo', 'A2', 26, 'Mô tả một bộ trang phục theo chất liệu, họa tiết, độ vừa vặn và nêu ý kiến của mình.', ARRAY['tính từ mô tả','danh từ chỉ chất liệu']::text[], 'It''s a striped cotton shirt, but it''s too tight.', 'Bảng so sánh trang phục: áo kẻ sọc, váy chấm bi, quần vải bò, áo lụa trơn, cùng cặp ảnh minh họa rộng và chật, dài và ngắn.', ARRAY['Describe the clothes you like to wear most.','What do you do when clothes are too big or too small?','Do you care more about price or quality when you buy clothes?']::text[]),
 ('CDS-U05-06', 'CDS-U05', 'CDS', 6, 'Doing the Laundry', 'Giặt giũ quần áo', 'A2', 22, 'Kể lại các bước giặt, phơi, gấp quần áo và nói cách mình xử lý vết bẩn.', ARRAY['động từ chỉ hành động','danh từ chỉ đồ dùng giặt giũ']::text[], 'I sort the clothes, then I hang them out to dry.', 'Bộ tranh năm ô: phân loại quần áo bẩn, cho vào máy giặt với bột giặt, phơi lên dây ngoài ban công, là quần áo, gấp xếp vào tủ.', ARRAY['Who does the laundry in your home?','How often do you wash your clothes?','What do you do when clothes will not dry in the rainy season?']::text[]),
 ('CDS-U05-07', 'CDS-U05', 'CDS', 7, 'Sewing and Alterations', 'May vá và sửa quần áo', 'B1', 24, 'Trình bày yêu cầu sửa quần áo với thợ may và mô tả chỗ hỏng cần khắc phục.', ARRAY['danh từ chỉ dụng cụ và chi tiết may','động từ chỉ thao tác sửa chữa']::text[], 'Could you take in the waist and shorten the sleeves?', 'Tiệm may nhỏ: máy khâu, kim chỉ, thước dây, kéo, cúc áo, khóa kéo, ma-nơ-canh mặc áo đang ghim sửa.', ARRAY['Have you ever had clothes altered? What was changed?','Do you repair clothes yourself or throw them away?','Is tailoring still common where you live? Why do you think so?']::text[]),
 ('CDS-U06-01', 'CDS-U06', 'CDS', 1, 'The Body', 'Cơ thể người', 'A1', 26, 'Gọi tên được các bộ phận cơ thể và chỉ đúng chỗ mình muốn nói tới.', ARRAY['danh từ đếm được','danh từ số nhiều bất quy tắc']::text[], 'This is my …; these are my …', 'Hình người đứng thẳng nhìn từ trước và sau, có đường chỉ dẫn tới đầu, vai, tay, bàn tay, ngón tay, lưng, chân, bàn chân.', ARRAY['Which part of your body do you use the most at work?','What do you do to keep your body strong?','How do you feel after a long day of standing or sitting?']::text[]),
 ('CDS-U06-02', 'CDS-U06', 'CDS', 2, 'Personal Hygiene', 'Vệ sinh cá nhân', 'A1', 24, 'Kể được thói quen vệ sinh cá nhân hằng ngày và gọi tên đồ dùng đi kèm.', ARRAY['động từ chỉ thói quen','danh từ chỉ đồ dùng cá nhân']::text[], 'Every morning I brush my teeth and wash my face.', 'Kệ nhà tắm bày bàn chải, kem đánh răng, xà phòng, dầu gội, khăn mặt, lược, dao cạo, kèm ô nhỏ vẽ người đang rửa tay.', ARRAY['What do you do first when you wake up?','How many times a day do you wash your hands?','What personal items do you take when you travel?']::text[]),
 ('CDS-U06-03', 'CDS-U06', 'CDS', 3, 'Symptoms and Injuries', 'Triệu chứng và chấn thương', 'A2', 24, 'Nói rõ mình đau ở đâu, đau từ bao giờ để người khác hiểu tình trạng của mình.', ARRAY['danh từ chỉ triệu chứng','động từ chỉ cảm giác đau']::text[], 'I have a … and it started two days ago.', 'Bộ tranh sáu ô: người ôm đầu, người sờ cổ họng, người che miệng ho, người xoa bụng, cổ tay bị bó, đầu gối trầy xước.', ARRAY['When did you last feel unwell? What did you tell people?','How do you describe pain in Vietnamese and in English?','What do you do when you feel too tired to work?']::text[]),
 ('CDS-U06-04', 'CDS-U06', 'CDS', 4, 'Illnesses and Medical Conditions', 'Bệnh thường gặp', 'B1', 26, 'Gọi tên các bệnh thường gặp và trình bày tiền sử bệnh của bản thân khi được hỏi.', ARRAY['danh từ chỉ bệnh','thì hiện tại hoàn thành']::text[], 'I''ve had … since I was a child.', 'Bộ thẻ tranh minh họa cảm cúm, sốt, dị ứng, hen suyễn, tiểu đường, cao huyết áp, kèm biểu tượng đơn giản cho mỗi mục.', ARRAY['Which illnesses are common in your area at this time of year?','How do people in your family talk about being sick?','What information would you give a doctor about your medical history?']::text[]),
 ('CDS-U06-05', 'CDS-U06', 'CDS', 5, 'Health Care', 'Dịch vụ y tế và bảo hiểm', 'B1', 24, 'Hỏi và trả lời về thẻ bảo hiểm, chi phí khám và các loại hình chăm sóc sức khỏe sẵn có.', ARRAY['danh từ chỉ dịch vụ','danh từ chỉ giấy tờ']::text[], 'Does my insurance cover this appointment?', 'Quầy tiếp nhận bệnh viện: nhân viên cầm thẻ bảo hiểm, tờ khai, hóa đơn, sau lưng là bảng chỉ dẫn các khoa.', ARRAY['How does health insurance work where you live?','What makes it easy or hard to see a doctor in your area?','If you could improve one thing about health services, what would it be?']::text[]),
 ('CDS-U06-06', 'CDS-U06', 'CDS', 6, 'Medical Emergencies', 'Tình huống cấp cứu', 'B1', 22, 'Gọi được số cấp cứu và cung cấp thông tin cần thiết về địa điểm cùng tình trạng người gặp nạn.', ARRAY['danh từ chỉ tình huống khẩn cấp','câu mệnh lệnh']::text[], 'We need an ambulance at … — someone is …', 'Cảnh đường phố ban đêm: xe cứu thương đèn nhấp nháy, nhân viên y tế mang cáng, người dân gọi điện thoại đứng chỉ đường.', ARRAY['What emergency number do people call where you live?','Describe a time you or someone near you needed urgent help.','What information should you give on an emergency call, and why?']::text[]),
 ('CDS-U06-07', 'CDS-U06', 'CDS', 7, 'First Aid', 'Hộp cứu thương và vật dụng sơ cứu', 'B1', 22, 'Gọi tên các vật dụng trong hộp cứu thương và nói được vật dụng nào dùng cho tình huống nào.', ARRAY['danh từ chỉ vật dụng y tế','cụm giới từ chỉ mục đích']::text[], 'There''s a … in the first aid kit for …', 'Hộp cứu thương mở nắp trên bàn: băng gạc, băng cá nhân, băng cuộn, gạc vô trùng, nhiệt kế, kéo, găng tay dùng một lần, nước muối sinh lý.', ARRAY['Is there a first aid kit at your home or workplace?','Which items do you think every kit should have?','Have you ever taken a first aid course? Would you like to?']::text[]),
 ('CDS-U06-08', 'CDS-U06', 'CDS', 8, 'Clinics', 'Phòng khám', 'A2', 22, 'Đặt lịch hẹn tại phòng khám và làm thủ tục nhận số khi đến nơi.', ARRAY['danh từ chỉ nơi chốn và người','động từ chỉ thủ tục']::text[], 'I''d like to make an appointment for …', 'Phòng chờ của phòng khám nhỏ: quầy lễ tân, bảng số thứ tự, ghế chờ có bệnh nhân ngồi, cửa phòng bác sĩ và phòng lấy máu.', ARRAY['When did you last go to a clinic?','Do you prefer a small clinic or a big hospital? Why?','How long do people usually wait to be seen where you live?']::text[]),
 ('CDS-U06-09', 'CDS-U06', 'CDS', 9, 'Medical and Dental Exams', 'Khám sức khỏe và khám răng', 'B1', 24, 'Hiểu và làm theo các yêu cầu thường gặp trong buổi khám tổng quát hoặc khám răng.', ARRAY['động từ chỉ thao tác khám','danh từ chỉ thiết bị khám']::text[], 'The nurse will check my … before the doctor comes in.', 'Bộ hai tranh: phòng khám tổng quát có máy đo huyết áp, ống nghe, cân, thước đo chiều cao; phòng nha có ghế nha khoa, đèn, gương soi răng, phim chụp răng.', ARRAY['How often do you have a general check-up?','What happens step by step at a dental visit you remember?','Why do some people avoid check-ups? What would change their mind?']::text[]),
 ('CDS-U06-10', 'CDS-U06', 'CDS', 10, 'A Hospital', 'Bệnh viện', 'B1', 26, 'Hỏi đường đến đúng khoa trong bệnh viện và gọi tên nhân viên, phòng ban, thiết bị thường gặp.', ARRAY['danh từ chỉ khoa phòng','danh từ chỉ nghề nghiệp']::text[], 'Could you tell me where the … department is?', 'Mặt cắt bệnh viện nhiều tầng: khoa cấp cứu, phòng mổ, phòng bệnh nhân với giường và màn hình theo dõi, khu chụp chiếu, hành lang có bảng chỉ dẫn.', ARRAY['Describe the last time you visited someone in hospital.','Which hospital staff do patients meet first, and what do they do?','What would make a hospital stay easier for a patient and their family?']::text[]),
 ('CDS-U07-01', 'CDS-U07', 'CDS', 1, 'City Streets', 'Phố phường', 'A2', 24, 'Gọi tên được các địa điểm trên phố và hỏi đường đến một nơi gần đó.', ARRAY['danh từ chỉ nơi chốn','giới từ chỉ vị trí']::text[], 'Is there a … near here?', 'Toàn cảnh một con phố đông đúc: hiệu thuốc, tiệm cắt tóc, quán cà phê, trạm xăng, trụ sở phường, vỉa hè có xe máy đỗ.', ARRAY['What places are on your street?','Which shop near your home do you go to most often?','How is your street different in the morning and at night?']::text[]),
 ('CDS-U07-02', 'CDS-U07', 'CDS', 2, 'An Intersection', 'Ngã tư đường', 'A2', 20, 'Mô tả được cảnh vật ở một ngã tư và nói cách qua đường an toàn.', ARRAY['danh từ chỉ hạ tầng đường phố','động từ chỉ di chuyển']::text[], 'Cross the street at the corner and turn …', 'Một ngã tư nhìn từ trên cao: đèn tín hiệu, vạch kẻ cho người đi bộ, biển tên đường, thùng rác, xe buýt đang dừng.', ARRAY['What do you see at a busy intersection?','How do you cross the street safely where you live?','Do drivers in your city stop for people walking? Why or why not?']::text[]),
 ('CDS-U07-03', 'CDS-U07', 'CDS', 3, 'A Mall', 'Trung tâm thương mại', 'A2', 22, 'Hỏi và chỉ được vị trí các gian hàng, dịch vụ bên trong trung tâm thương mại.', ARRAY['danh từ chỉ cửa hàng và dịch vụ','số thứ tự chỉ tầng']::text[], 'Excuse me, where is the …? — It''s on the second floor.', 'Bên trong một trung tâm thương mại nhiều tầng: thang cuốn, bảng chỉ dẫn, khu ăn uống, quầy thông tin, cửa hàng quần áo và điện thoại.', ARRAY['What do you usually do at a shopping mall?','Which floor do you go to first, and why?','Do you prefer a mall or a local market? Tell me why.']::text[]),
 ('CDS-U07-04', 'CDS-U07', 'CDS', 4, 'A Childcare Center', 'Nhà trẻ', 'A2', 22, 'Hỏi được thông tin về một nhà trẻ và nói về việc chăm sóc trẻ nhỏ hằng ngày.', ARRAY['danh từ chỉ đồ dùng trẻ em','động từ chỉ hoạt động chăm sóc']::text[], 'What time do you drop off and pick up your child?', 'Một phòng nhà trẻ sáng sủa: cũi, ghế cao, đồ chơi xếp hình, giá để ba lô, cô giáo đang đọc truyện cho nhóm trẻ ngồi trên thảm.', ARRAY['What do small children do all day at a childcare center?','What should parents ask before they choose one?','Who takes care of young children in your family?']::text[]),
 ('CDS-U07-05', 'CDS-U07', 'CDS', 5, 'Mail and Post Office', 'Bưu điện và thư từ', 'A2', 24, 'Gửi được thư hoặc bưu kiện tại bưu điện và ghi đúng địa chỉ trên phong bì.', ARRAY['danh từ chỉ bưu phẩm','động từ chỉ quy trình gửi nhận']::text[], 'I''d like to send this package to …', 'Quầy bưu điện: nhân viên cân bưu kiện, khách cầm phong bì và tem, hộp thư màu vàng, kệ hộp giấy các cỡ ở phía sau.', ARRAY['When was the last time you sent something by mail?','What do you write on an envelope before you send it?','Do people still send letters in your country? Why or why not?']::text[]),
 ('CDS-U07-06', 'CDS-U07', 'CDS', 6, 'A Bank', 'Ngân hàng', 'A2', 24, 'Thực hiện được giao dịch cơ bản ở ngân hàng như gửi, rút tiền và mở tài khoản.', ARRAY['danh từ chỉ dịch vụ ngân hàng','động từ chỉ giao dịch']::text[], 'I''d like to open an account, please.', 'Sảnh ngân hàng: quầy giao dịch viên, khách xếp hàng lấy số, máy ATM ngoài sảnh, bảng tỉ giá điện tử trên tường.', ARRAY['What do you usually do at the bank?','Do you prefer using an app or going to the bank? Why?','What information does a bank ask for when you open an account?']::text[]),
 ('CDS-U07-07', 'CDS-U07', 'CDS', 7, 'A Library', 'Thư viện', 'A2', 22, 'Mượn và trả được sách ở thư viện, hỏi tìm tài liệu mình cần.', ARRAY['danh từ chỉ tài liệu và khu vực','động từ chỉ mượn trả']::text[], 'How long can I borrow this book for?', 'Bên trong thư viện: giá sách cao, quầy thủ thư, bàn đọc có đèn, khu máy tính tra cứu, bảng nội quy giữ im lặng.', ARRAY['What kind of books do you like to borrow?','Is there a library near your home or school?','How can a library help someone learning a new language?']::text[]),
 ('CDS-U07-08', 'CDS-U07', 'CDS', 8, 'The Legal System', 'Hệ thống pháp luật', 'B1', 26, 'Mô tả được các bước cơ bản của một vụ án và vai trò của những người trong phiên tòa.', ARRAY['danh từ chỉ người và cơ quan','động từ chỉ thủ tục tố tụng']::text[], 'The case was heard in court last week.', 'Bộ tranh phòng xử án: thẩm phán ngồi trên bục, luật sư đứng trình bày, thư ký ghi biên bản, hàng ghế người dự khán.', ARRAY['What do you think a fair trial should look like?','Why is it important that everyone can have a lawyer?','Where would you look for reliable information about your rights?']::text[]),
 ('CDS-U07-09', 'CDS-U07', 'CDS', 9, 'Crime', 'Tội phạm', 'B1', 22, 'Gọi tên được các loại vi phạm thường gặp và tường thuật lại một sự việc cho cơ quan chức năng.', ARRAY['danh từ chỉ hành vi vi phạm','động từ tường thuật']::text[], 'I''d like to report a …', 'Bộ tranh nhỏ mô tả tình huống: một chiếc ví bị mất trong đám đông, camera an ninh trên tường, người dân trình báo tại quầy công an phường.', ARRAY['What makes a neighborhood feel safe to you?','What should a person do if their phone or wallet is stolen?','How can neighbors help each other prevent problems?']::text[]),
 ('CDS-U07-10', 'CDS-U07', 'CDS', 10, 'Public Safety', 'An toàn công cộng', 'A2', 20, 'Đưa ra được lời khuyên giữ an toàn cho bản thân ở nơi công cộng.', ARRAY['động từ chỉ hành động phòng ngừa','danh từ chỉ thiết bị an toàn']::text[], 'You should always lock the door.', 'Bộ tranh lời khuyên an toàn: khóa cửa, đi bộ ở nơi có đèn sáng, cất túi xách cẩn thận, đội mũ bảo hiểm, để ý người lạ.', ARRAY['What do you do to stay safe when you go out at night?','What safety advice would you give a new student in your city?','Which places in your area feel the safest?']::text[]),
 ('CDS-U07-11', 'CDS-U07', 'CDS', 11, 'Emergencies and Natural Disasters', 'Khẩn cấp và thiên tai', 'B1', 28, 'Gọi tên được các loại thiên tai, sự cố khẩn cấp và trình bày cách chuẩn bị ứng phó.', ARRAY['danh từ chỉ hiện tượng thiên tai','động từ chỉ ứng phó']::text[], 'In case of a flood, you should …', 'Bộ tranh thiên tai: bão và mưa lớn, đường phố ngập nước, cháy nhà, động đất làm nứt tường, kèm túi đồ dùng khẩn cấp có đèn pin và nước.', ARRAY['Which natural disasters happen most often where you live?','What would you put in an emergency bag for your family?','How do people in your area get warnings before a storm?']::text[]),
 ('CDS-U08-01', 'CDS-U08', 'CDS', 1, 'Public Transportation', 'Giao thông công cộng', 'A2', 24, 'Mua vé và hỏi được thông tin tuyến, giờ chạy của phương tiện công cộng.', ARRAY['danh từ chỉ phương tiện','danh từ chỉ vé và bến bãi']::text[], 'Which bus goes to …?', 'Bến xe buýt và ga tàu điện: bảng giờ chạy, máy bán vé tự động, hành khách chờ trên sân ga, tài xế xe buýt mở cửa.', ARRAY['How do you get to work or school every day?','What do you like or dislike about buses in your city?','How much does a single ticket cost where you live?']::text[]),
 ('CDS-U08-02', 'CDS-U08', 'CDS', 2, 'Prepositions of Motion', 'Giới từ chỉ chuyển động', 'A1', 14, 'Mô tả được hướng di chuyển của người và xe bằng giới từ chỉ chuyển động.', ARRAY['giới từ chỉ hướng','động từ chỉ di chuyển']::text[], 'She''s getting on the bus.', 'Chuỗi hình đơn giản: người bước lên xe buýt, xuống tàu, đi qua cầu, chạy vào cửa hàng, đi vòng quanh công viên.', ARRAY['How do you get on a bus?','Do you walk into a shop or drive past it?','What do you go through on your way home?']::text[]),
 ('CDS-U08-03', 'CDS-U08', 'CDS', 3, 'Cars and Trucks', 'Ô tô và xe tải', 'A2', 20, 'Phân biệt và gọi tên được các loại xe theo mục đích sử dụng.', ARRAY['danh từ chỉ loại xe','tính từ mô tả kích cỡ']::text[], 'A … is bigger than a …', 'Bãi xe trưng bày nhiều loại: xe con, xe bán tải, xe tải thùng, xe khách, xe cứu thương, xe chở hàng lạnh.', ARRAY['What kind of vehicle would you like to have? Why?','Which vehicles do you see most on your street?','Is a big car useful in a crowded city? Tell me your idea.']::text[]),
 ('CDS-U08-04', 'CDS-U08', 'CDS', 4, 'Directions and Traffic Signs', 'Chỉ đường và biển báo', 'A2', 24, 'Chỉ đường cho người khác và hiểu được ý nghĩa các biển báo giao thông thường gặp.', ARRAY['động từ mệnh lệnh chỉ đường','danh từ chỉ biển báo']::text[], 'Go straight, then turn left at the traffic light.', 'Bộ biển báo phổ biến kèm một bản đồ nhỏ có mũi tên: dừng lại, cấm rẽ, một chiều, đường trơn, khu vực trường học.', ARRAY['How do you get from your home to the nearest market?','Which traffic sign do you think people ignore the most?','Do you use a map app or ask people for directions? Why?']::text[]),
 ('CDS-U08-05', 'CDS-U08', 'CDS', 5, 'Parts of a Car and Car Maintenance', 'Bộ phận xe và bảo dưỡng', 'B1', 28, 'Gọi tên được các bộ phận chính của xe và mô tả một hỏng hóc cho thợ sửa.', ARRAY['danh từ chỉ bộ phận xe','động từ chỉ việc sửa chữa']::text[], 'There''s something wrong with the …', 'Hình cắt lớp một chiếc ô tô chú thích bộ phận, cạnh đó là gara với thợ đang thay lốp và kiểm tra dầu máy.', ARRAY['How often should a car or motorbike be checked?','Describe a time when a vehicle broke down. What did you do?','Do you fix small problems yourself or take it to a mechanic? Why?']::text[]),
 ('CDS-U08-06', 'CDS-U08', 'CDS', 6, 'An Airport', 'Sân bay', 'A2', 26, 'Làm được thủ tục ở sân bay và hỏi thông tin về chuyến bay, cửa ra máy bay.', ARRAY['danh từ chỉ khu vực sân bay','động từ chỉ thủ tục']::text[], 'Where do I check in for flight …?', 'Nhà ga sân bay: quầy làm thủ tục, máy soi hành lý, bảng điện tử báo chuyến bay, cửa ra máy bay, băng chuyền hành lý.', ARRAY['How early do you arrive at the airport before a flight?','What happens at security check?','What is the hardest part of travelling by plane for you?']::text[]),
 ('CDS-U08-07', 'CDS-U08', 'CDS', 7, 'A Plane Trip', 'Chuyến bay', 'A2', 24, 'Mô tả được trình tự một chuyến bay và trao đổi với tiếp viên về nhu cầu trên máy bay.', ARRAY['danh từ chỉ đồ vật trên máy bay','động từ chỉ trình tự chuyến bay']::text[], 'Could I have a glass of water, please?', 'Khoang máy bay đang bay: hành khách thắt dây an toàn, tiếp viên đẩy xe đồ ăn, khoang hành lý phía trên, cửa sổ nhìn ra mây.', ARRAY['Do you prefer a window seat or an aisle seat? Why?','What do you do to pass the time on a long flight?','Tell me about a flight you remember well.']::text[]),
 ('CDS-U09-01', 'CDS-U09', 'CDS', 1, 'Types of Schools', 'Các loại trường học', 'A2', 20, 'Phân biệt được các cấp học, loại trường và nói về con đường học tập của mình.', ARRAY['danh từ chỉ loại trường','động từ chỉ việc học']::text[], 'I studied at a … for … years.', 'Bộ tranh cổng các loại trường: mầm non, tiểu học, trung học, trường nghề, đại học, trung tâm ngoại ngữ buổi tối.', ARRAY['What kind of school did you go to?','What can students learn at a vocational school?','At what age do children start school in your country?']::text[]),
 ('CDS-U09-02', 'CDS-U09', 'CDS', 2, 'English Composition', 'Tập làm văn tiếng Anh', 'B1', 24, 'Mô tả được các bước viết một bài luận ngắn và gọi tên các phần của bài viết.', ARRAY['danh từ chỉ thành phần bài viết','động từ chỉ quy trình viết']::text[], 'First I write an outline, then I write a draft.', 'Bàn học có bản nháp bài luận gạch xóa, dàn ý ghi trên giấy nhớ, bút đỏ sửa lỗi, laptop mở trang soạn thảo.', ARRAY['What is the hardest part of writing in English for you?','How do you plan a piece of writing before you start?','Do you find it easier to write or to speak? Explain why.']::text[]),
 ('CDS-U09-03', 'CDS-U09', 'CDS', 3, 'History', 'Lịch sử', 'B1', 26, 'Kể lại được một giai đoạn hay sự kiện lịch sử bằng thì quá khứ và mốc thời gian.', ARRAY['danh từ chỉ thời kỳ và sự kiện','động từ ở thì quá khứ']::text[], 'It happened in the … century.', 'Trục thời gian trên bảng lớp với các cột mốc và tranh minh họa trung lập: hiện vật khảo cổ, bản đồ cổ, tài liệu viết tay, đài tưởng niệm.', ARRAY['Which period of history in your country interests you most? Why?','Tell me about a historical place you have visited.','Why do you think people should study history?']::text[]),
 ('CDS-U09-04', 'CDS-U09', 'CDS', 4, 'Government and Citizenship', 'Chính quyền và công dân', 'B1', 26, 'Nói được về các cấp chính quyền, quyền và nghĩa vụ cơ bản của một công dân.', ARRAY['danh từ chỉ cơ quan và chức danh','danh từ trừu tượng chỉ quyền và nghĩa vụ']::text[], 'Every citizen has the right to …', 'Bộ tranh trung lập: sơ đồ các cấp chính quyền từ địa phương đến trung ương, người dân nộp hồ sơ ở cơ quan hành chính, hòm phiếu, thẻ căn cước.', ARRAY['What services does your local government provide?','What responsibilities do you think a good citizen has?','Which public service in your area would you improve, and how?']::text[]),
 ('CDS-U09-05', 'CDS-U09', 'CDS', 5, 'Geography', 'Địa lý', 'A2', 24, 'Gọi tên được các dạng địa hình và mô tả cảnh quan một vùng đất.', ARRAY['danh từ chỉ địa hình','tính từ mô tả cảnh quan']::text[], 'There are many mountains in the north.', 'Bức tranh toàn cảnh gộp nhiều dạng địa hình: núi, đồi, sông, hồ, thác, đồng bằng, sa mạc, bờ biển và đảo.', ARRAY['What is the land like in your home province?','Do you prefer mountains or the sea? Why?','Which landscape in your country should visitors see?']::text[]),
 ('CDS-U09-06', 'CDS-U09', 'CDS', 6, 'Mathematics', 'Toán học', 'A2', 24, 'Đọc và nói được các phép tính, hình học cơ bản bằng tiếng Anh.', ARRAY['danh từ chỉ phép tính và hình','động từ chỉ thao tác tính toán']::text[], 'Six plus four equals ten.', 'Bảng lớp môn toán: phép cộng trừ nhân chia, phân số, các hình tròn, vuông, tam giác có ghi kích thước, thước kẻ và máy tính bỏ túi.', ARRAY['Do you like maths? Why or why not?','When do you use numbers in your daily life?','How do you calculate a discount when you go shopping?']::text[]),
 ('CDS-U09-07', 'CDS-U09', 'CDS', 7, 'Science', 'Khoa học', 'B1', 26, 'Mô tả được dụng cụ thí nghiệm và trình bày các bước của một thí nghiệm đơn giản.', ARRAY['danh từ chỉ dụng cụ thí nghiệm','động từ chỉ thao tác nghiên cứu']::text[], 'We heated the liquid and recorded the result.', 'Phòng thí nghiệm trường học: ống nghiệm, kính hiển vi, cân điện tử, đèn cồn, học sinh đeo kính bảo hộ ghi chép kết quả.', ARRAY['Which science subject did you enjoy most at school?','Describe a simple experiment you have done or seen.','How does science change everyday life in your country?']::text[]),
 ('CDS-U09-08', 'CDS-U09', 'CDS', 8, 'Music', 'Âm nhạc', 'A2', 22, 'Gọi tên được nhạc cụ, thể loại nhạc và nói về sở thích âm nhạc của mình.', ARRAY['danh từ chỉ nhạc cụ','danh từ chỉ thể loại nhạc']::text[], 'I like listening to … music.', 'Ban nhạc học sinh đang tập: đàn guitar, trống, piano, sáo, violin, kèm giá nhạc có bản nhạc và micro.', ARRAY['What kind of music do you listen to?','Can you play any instrument? Which one would you like to learn?','When do people in your country sing together?']::text[]),
 ('CDS-U09-09', 'CDS-U09', 'CDS', 9, 'More School Subjects', 'Các môn học khác', 'A2', 22, 'Gọi tên được các môn học ở trường và nói về môn mình thích hay thấy khó.', ARRAY['danh từ chỉ môn học','tính từ đánh giá độ khó']::text[], 'My favorite subject is …, but … is difficult for me.', 'Thời khóa biểu treo tường kèm biểu tượng từng môn: mỹ thuật, thể dục, tin học, ngoại ngữ, giáo dục công dân, kỹ thuật.', ARRAY['Which subject was your favorite at school? Why?','Which subject did you find the most difficult?','What subject do you think schools should teach more of?']::text[]),
 ('CDS-U09-10', 'CDS-U09', 'CDS', 10, 'Regions and Countries', 'Vùng miền và quốc gia', 'A2', 24, 'Nói được vị trí của một vùng, một quốc gia và mô tả đặc điểm nổi bật của nơi đó.', ARRAY['danh từ chỉ vùng miền và quốc gia','tính từ chỉ quốc tịch']::text[], 'It''s in the south of …, next to …', 'Bản đồ thế giới trống có tô màu các châu lục, kèm la bàn chỉ bốn hướng và vài cờ nhỏ để trên bàn học.', ARRAY['Which region of your country do you come from?','How is the north different from the south where you live?','Which country would you most like to visit? Why?']::text[]),
 ('CDS-U09-11', 'CDS-U09', 'CDS', 11, 'The World', 'Thế giới', 'A2', 22, 'Gọi tên được các châu lục, đại dương và định vị một nơi trên bản đồ thế giới.', ARRAY['danh từ chỉ châu lục và đại dương','giới từ chỉ vị trí địa lý']::text[], '… is in Southeast Asia.', 'Quả địa cầu lớn cạnh bản đồ thế giới chú thích châu lục, đại dương, đường xích đạo và hai cực.', ARRAY['Which continents can you name in English?','Where is your country on the world map?','Which ocean or sea is closest to your home?']::text[]),
 ('CDS-U09-12', 'CDS-U09', 'CDS', 12, 'Energy and the Environment', 'Năng lượng và môi trường', 'B1', 28, 'Trình bày được các nguồn năng lượng, vấn đề môi trường và đề xuất cách bảo vệ môi trường.', ARRAY['danh từ chỉ nguồn năng lượng','danh từ chỉ vấn đề môi trường']::text[], 'We should use less … to reduce pollution.', 'Bộ tranh đối lập: nhà máy nhả khói và rác thải nhựa trên sông ở một bên, tấm pin mặt trời, tua bin gió và thùng phân loại rác ở bên kia.', ARRAY['What environmental problem worries you most in your city?','How could your family use less electricity and water?','Do you think clean energy can replace coal and oil? Why?']::text[]),
 ('CDS-U09-13', 'CDS-U09', 'CDS', 13, 'The Universe', 'Vũ trụ', 'B1', 24, 'Gọi tên được các thiên thể và mô tả hiện tượng thiên văn bằng câu đơn giản.', ARRAY['danh từ chỉ thiên thể','động từ chỉ chuyển động thiên văn']::text[], 'The Earth goes around the Sun.', 'Bầu trời đêm với hệ mặt trời minh họa: các hành tinh theo quỹ đạo, mặt trăng khuyết, sao chổi, kèm kính thiên văn đặt trên đồi.', ARRAY['What do you know about the planets in our solar system?','Have you ever watched the stars or an eclipse? Describe it.','Do you think humans should spend money on space travel? Why?']::text[]),
 ('CDS-U10-01', 'CDS-U10', 'CDS', 1, 'Trees and Plants', 'Cây cối', 'A1', 20, 'Gọi tên được các loại cây quen thuộc và các bộ phận của cây bằng câu đơn giản.', ARRAY['danh từ đếm được','danh từ không đếm được']::text[], 'This is a … / These are …', 'Một góc vườn và bìa rừng ở Việt Nam: cây xoài, bụi tre, cây dừa, cỏ dại, kèm ba hình cận cảnh rễ, thân, cành và lá.', ARRAY['What trees grow near your house?','Do you like planting trees? Why?','Which tree is the most common in your hometown?']::text[]),
 ('CDS-U10-02', 'CDS-U10', 'CDS', 2, 'Flowers', 'Các loài hoa', 'A1', 18, 'Nhận biết và gọi tên được các loài hoa phổ biến, mô tả màu sắc và mùi hương của chúng.', ARRAY['danh từ chỉ loài hoa','tính từ chỉ màu sắc']::text[], 'I like … because they are …', 'Một sạp hoa ngoài chợ với hoa hồng, hoa cúc, hoa sen, hoa lan xếp thành từng bó, kèm hình cắt cận cảnh cánh hoa, nhụy và cuống.', ARRAY['What is your favorite flower?','When do people give flowers in Viet Nam?','Are there any flowers in your home now?']::text[]),
 ('CDS-U10-03', 'CDS-U10', 'CDS', 3, 'Marine Life, Amphibians, and Reptiles', 'Sinh vật biển, lưỡng cư và bò sát', 'A2', 26, 'Mô tả được nơi sống và đặc điểm của các loài cá, lưỡng cư, bò sát bằng câu ghép đơn giản.', ARRAY['danh từ chỉ động vật','động từ chỉ chuyển động']::text[], 'A … lives in … and it can …', 'Bộ tranh ba mảng: rạn san hô có cá và rùa biển, ao sen có ếch và nòng nọc, bờ sông có cá sấu và thằn lằn phơi nắng.', ARRAY['Which sea animal do you find most interesting, and why?','Have you ever been to an aquarium or a fish market? What did you see there?','Why do you think many people are afraid of snakes and frogs?']::text[]),
 ('CDS-U10-04', 'CDS-U10', 'CDS', 4, 'Birds, Insects, and Arachnids', 'Chim, côn trùng và nhện', 'A2', 26, 'Gọi tên và so sánh được các loài chim, côn trùng thường gặp theo nơi sống và tập tính.', ARRAY['danh từ số nhiều','động từ chỉ hành động']::text[], '… have … and they can …', 'Khu vườn buổi sáng: chim sẻ đậu trên dây điện, ong bay quanh khóm hoa, bướm, đàn kiến bò trên đất và mạng nhện đọng sương giữa hai cành.', ARRAY['What birds or insects do you often see around your home?','Which insects are useful for farmers? Explain your answer.','Do you think people should keep birds in cages? Why or why not?']::text[]),
 ('CDS-U10-05', 'CDS-U10', 'CDS', 5, 'Domestic Animals and Rodents', 'Vật nuôi và loài gặm nhấm', 'A1', 20, 'Gọi tên được các con vật nuôi trong nhà, trong trang trại và nói về việc chăm sóc chúng.', ARRAY['danh từ chỉ con vật','động từ thường']::text[], 'I have a … / My … likes to …', 'Sân nhà ở vùng quê: chó nằm trước hiên, mèo trên bậu cửa, đàn gà vịt, chuồng lợn, thỏ trong lồng và một con chuột nhỏ chạy ở góc bếp.', ARRAY['Do you have a pet? Tell me about it.','What animals do farmers keep in your area?','What food do you give to a dog or a cat?']::text[]),
 ('CDS-U10-06', 'CDS-U10', 'CDS', 6, 'Mammals', 'Động vật có vú', 'A2', 24, 'Miêu tả được ngoại hình, tập tính và môi trường sống của các loài thú bằng câu so sánh.', ARRAY['danh từ chỉ động vật hoang dã','tính từ so sánh']::text[], 'A … is bigger / faster than a …', 'Tranh ghép động vật hoang dã: voi và hổ trong rừng nhiệt đới, khỉ chuyền cành, gấu, hươu sao, cá voi và cá heo ngoài khơi.', ARRAY['Which wild animal would you like to see in real life, and why?','How is a zoo different from a national park?','What can people do to protect wild animals in Viet Nam?']::text[]),
 ('CDS-U11-01', 'CDS-U11', 'CDS', 1, 'Jobs and Occupations, A–H', 'Nghề nghiệp (phần 1: A–H)', 'A1', 24, 'Gọi tên được các nghề có tên bắt đầu từ A đến H và nói người đó làm việc ở đâu.', ARRAY['danh từ chỉ nghề nghiệp','mạo từ a/an']::text[], 'He is an engineer. / She works in a …', 'Bộ chân dung nghề nghiệp nửa đầu bảng chữ cái: kế toán, thợ làm bánh, thợ hớt tóc, đầu bếp, nha sĩ, kỹ sư, nông dân, thợ làm tóc, mỗi người kèm dụng cụ đặc trưng.', ARRAY['What is your job, or what job do you want?','Who is a cook or a farmer in your family?','Where does a dentist work?']::text[]),
 ('CDS-U11-02', 'CDS-U11', 'CDS', 2, 'Jobs and Occupations, H–W', 'Nghề nghiệp (phần 2: H–W)', 'A1', 24, 'Gọi tên được các nghề có tên bắt đầu từ H đến W và kể được công việc chính hằng ngày của họ.', ARRAY['danh từ chỉ nghề nghiệp','động từ ở thì hiện tại đơn']::text[], 'A nurse helps patients. / A writer writes …', 'Bộ chân dung nghề nghiệp nửa sau bảng chữ cái: y tá, thợ máy, cảnh sát, thợ ống nước, giáo viên, nhân viên bán hàng, tài xế, nhà văn, mỗi người trong bối cảnh làm việc thật.', ARRAY['What does a nurse do every day?','Which job on this list looks the hardest to you?','Do you know a teacher or a driver? Tell me about their work.']::text[]),
 ('CDS-U11-03', 'CDS-U11', 'CDS', 3, 'Job Skills', 'Kỹ năng nghề', 'A2', 20, 'Trình bày được những việc mình làm được và chưa làm được trong công việc bằng cấu trúc can/can''t.', ARRAY['động từ khuyết thiếu can','cụm động từ chỉ kỹ năng']::text[], 'I can … / I can''t … yet.', 'Bảng ghép sáu tình huống kỹ năng: nhập liệu trên máy tính, phục vụ khách hàng, sửa máy móc, lái xe nâng, chăm sóc người bệnh, nấu ăn số lượng lớn.', ARRAY['What can you do well at work or at school?','Which skill would you like to learn this year, and why?','How did you learn your most useful skill?']::text[]),
 ('CDS-U11-04', 'CDS-U11', 'CDS', 4, 'Job Search', 'Tìm việc', 'B1', 22, 'Mô tả được toàn bộ quá trình xin việc, từ tìm tin tuyển dụng đến phỏng vấn, bằng ngôn ngữ trang trọng.', ARRAY['danh từ trừu tượng','cụm động từ chỉ thủ tục']::text[], 'I''d like to apply for the position of …', 'Chuỗi bốn cảnh nối tiếp: đọc tin tuyển dụng trên điện thoại, soạn CV trên máy tính, nộp hồ sơ tại quầy, và buổi phỏng vấn qua bàn làm việc.', ARRAY['What makes a job application stand out to an employer?','How would you prepare for an interview in English?','Is salary or working environment more important when choosing a job? Explain your view.']::text[]),
 ('CDS-U11-05', 'CDS-U11', 'CDS', 5, 'An Office', 'Văn phòng', 'A2', 24, 'Gọi tên được trang thiết bị văn phòng và mô tả công việc diễn ra hằng ngày ở đó.', ARRAY['danh từ chỉ đồ dùng','động từ chỉ hoạt động văn phòng']::text[], 'Could you … the …, please?', 'Văn phòng mở nhìn từ trên xuống: dãy bàn làm việc, máy in, máy photocopy, tủ hồ sơ, phòng họp có máy chiếu và quầy lễ tân phía cửa.', ARRAY['What equipment do people use most in an office?','Describe a typical morning in an office you know.','Would you rather work in an office or from home? Why?']::text[]),
 ('CDS-U11-06', 'CDS-U11', 'CDS', 6, 'Computers', 'Máy tính', 'A2', 22, 'Gọi tên được các bộ phận của máy tính và hướng dẫn người khác thao tác cơ bản theo trình tự.', ARRAY['danh từ chỉ thiết bị','động từ ở dạng mệnh lệnh']::text[], 'First, click on … Then, save the file.', 'Bàn làm việc có máy tính để bàn và laptop: màn hình, bàn phím, chuột, USB, máy in; kèm hình cận cảnh màn hình đang mở thư mục và nút lưu.', ARRAY['What do you use a computer or a phone for every day?','Explain how to save a file and send it to a friend.','What is one computer problem you have had, and how did you fix it?']::text[]),
 ('CDS-U11-07', 'CDS-U11', 'CDS', 7, 'A Hotel', 'Khách sạn', 'A2', 22, 'Đặt phòng và nêu yêu cầu tại khách sạn bằng các mẫu câu lịch sự.', ARRAY['danh từ chỉ khu vực và nhân viên','câu yêu cầu lịch sự']::text[], 'I''d like to book a room for … nights.', 'Khách sạn cắt dọc nhìn xuyên tầng: quầy lễ tân, nhân viên khuân hành lý, thang máy, phòng ngủ đôi và nhân viên buồng phòng đẩy xe khăn ngoài hành lang.', ARRAY['What do you look at first when you choose a hotel?','Describe the last place you stayed away from home.','What would you say if your hotel room was too noisy?']::text[]),
 ('CDS-U11-08', 'CDS-U11', 'CDS', 8, 'A Factory', 'Nhà máy', 'B1', 22, 'Mô tả được quy trình sản xuất trong nhà máy và vai trò của từng bộ phận bằng câu bị động.', ARRAY['câu bị động','danh từ chỉ quy trình sản xuất']::text[], 'The parts are assembled on the …', 'Xưởng sản xuất rộng: dây chuyền lắp ráp, công nhân đeo khẩu trang và mũ bảo hộ, xe nâng chở pallet, khu kiểm tra chất lượng và kho thành phẩm.', ARRAY['How is a product made, from raw material to packaging?','What are the good and bad sides of working in a factory?','How do you think automation will change factory jobs in Viet Nam?']::text[]),
 ('CDS-U11-09', 'CDS-U11', 'CDS', 9, 'Job Safety', 'An toàn lao động', 'A2', 20, 'Nhận biết được biển báo an toàn và gọi tên đồ bảo hộ cần dùng ở nơi làm việc.', ARRAY['danh từ chỉ đồ bảo hộ','câu mệnh lệnh khẳng định và phủ định']::text[], 'You must wear … here. / Don''t … in this area.', 'Bảng biển báo an toàn màu vàng và đỏ treo cạnh giá đồ bảo hộ: mũ cứng, kính bảo hộ, găng tay, nút bịt tai, khẩu trang, giày mũi thép, áo phản quang.', ARRAY['What safety equipment do workers wear in your workplace?','Which safety signs do you see most often, and what do they mean?','What should a new worker learn about safety on the first day?']::text[]),
 ('CDS-U11-10', 'CDS-U11', 'CDS', 10, 'Farming and Ranching', 'Nông nghiệp và chăn nuôi', 'A2', 24, 'Kể lại được các công việc theo mùa vụ trên đồng ruộng và trong trang trại.', ARRAY['động từ chỉ hoạt động nông nghiệp','danh từ chỉ cây trồng và vật nuôi']::text[], 'Farmers plant … in … and harvest it in …', 'Cánh đồng lúa Việt Nam vào vụ gặt: máy cày, người cấy lúa, đàn trâu bò, vườn cây ăn quả, chuồng gà và ao cá phía sau nhà.', ARRAY['What crops or animals are raised in your home province?','Describe the work farmers do in one season of the year.','Why do many young people leave farm work today?']::text[]),
 ('CDS-U11-11', 'CDS-U11', 'CDS', 11, 'Construction', 'Công trường xây dựng', 'A2', 24, 'Gọi tên được máy móc, vật liệu trên công trường và mô tả các bước xây một ngôi nhà.', ARRAY['danh từ chỉ vật liệu','động từ chỉ thao tác']::text[], 'They are building a … / The workers use a … to …', 'Công trường xây nhà phố: giàn giáo, cần cẩu, máy trộn bê tông, đống gạch và cát, xe ben đổ vật liệu, công nhân đội mũ bảo hộ làm việc trên tầng hai.', ARRAY['What machines have you seen on a construction site?','Describe the steps of building a small house.','Is there any new construction near your home? What is being built?']::text[]),
 ('CDS-U11-12', 'CDS-U11', 'CDS', 12, 'Tools and Building Supplies', 'Dụng cụ và vật tư xây dựng', 'A2', 26, 'Gọi tên được dụng cụ cầm tay, vật tư xây dựng và nói mình dùng chúng để làm gì.', ARRAY['danh từ chỉ dụng cụ','cấu trúc chỉ mục đích với to V']::text[], 'You use a … to …', 'Cửa hàng vật tư với thùng dụng cụ mở nắp: búa, tua vít, cờ lê, kìm, cưa, máy khoan, hộp đinh vít, băng keo, thùng sơn và thước dây.', ARRAY['Which tools do you have at home?','Explain how to hang a picture on the wall.','Have you ever repaired something yourself? What happened?']::text[]),
 ('CDS-U12-01', 'CDS-U12', 'CDS', 1, 'Places to Go', 'Những nơi vui chơi', 'A1', 20, 'Nói được mình muốn đi đâu vào ngày nghỉ và rủ người khác cùng đi.', ARRAY['danh từ chỉ địa điểm','cấu trúc rủ rê Let''s']::text[], 'Let''s go to the … on Sunday.', 'Bản đồ vui chơi của một thành phố: sở thú, bảo tàng, công viên nước, rạp chiếu phim, chợ đêm và khu trò chơi trẻ em, mỗi nơi một ô tranh nhỏ.', ARRAY['Where do you go on your day off?','Do you like the zoo or the museum? Why?','Who do you go out with?']::text[]),
 ('CDS-U12-02', 'CDS-U12', 'CDS', 2, 'The Park and Playground', 'Công viên và sân chơi', 'A1', 20, 'Gọi tên được thiết bị trong công viên, sân chơi và nói mọi người đang làm gì ở đó.', ARRAY['danh từ chỉ đồ vật','thì hiện tại tiếp diễn']::text[], 'The children are playing on the …', 'Công viên buổi chiều: cầu trượt, xích đu, bập bênh, hố cát, ghế đá, đường chạy bộ, người tập thể dục và trẻ em thả diều.', ARRAY['Is there a park near your house?','What do children do at the playground?','What do you like doing in a park?']::text[]),
 ('CDS-U12-03', 'CDS-U12', 'CDS', 3, 'Outdoor Recreation', 'Hoạt động ngoài trời', 'A2', 22, 'Lên kế hoạch cho một chuyến đi ngoài trời và liệt kê được đồ dùng cần mang theo.', ARRAY['danh từ chỉ dụng cụ','động từ chỉ hoạt động ngoài trời']::text[], 'We''re going to … We need to bring …', 'Khu cắm trại bên hồ: lều, túi ngủ, bếp ga mini, đống lửa, ba lô, cần câu, xe đạp địa hình và lối mòn leo núi phía xa.', ARRAY['Have you ever been camping? Tell me about it.','What do you need to bring for a day in the mountains?','Why do some people prefer holidays in nature to holidays in the city?']::text[]),
 ('CDS-U12-04', 'CDS-U12', 'CDS', 4, 'The Beach', 'Bãi biển', 'A1', 20, 'Mô tả được cảnh vật và hoạt động ở bãi biển bằng câu đơn giản.', ARRAY['danh từ chỉ sự vật','cấu trúc there is / there are']::text[], 'There is a … / There are … on the beach.', 'Bãi biển miền Trung buổi sáng: sóng, cát, dù che nắng, ghế bố, phao bơi, thuyền thúng, người bán hàng rong và trẻ em xây lâu đài cát.', ARRAY['Do you like the beach? Why?','What do you take to the beach?','Which beach in Viet Nam do you want to visit?']::text[]),
 ('CDS-U12-05', 'CDS-U12', 'CDS', 5, 'Sports Verbs', 'Động từ thể thao', 'A2', 20, 'Dùng đúng động từ chỉ động tác thể thao khi tường thuật một pha thi đấu ngắn.', ARRAY['động từ chỉ động tác','thì hiện tại tiếp diễn']::text[], 'He is throwing the ball and she is catching it.', 'Chuỗi tám khung hình động tác nhỏ: ném, bắt, đá, chạy, nhảy, bơi, ném rổ và đánh vợt, mỗi khung một vận động viên.', ARRAY['Which sports actions are you good at?','Describe what the players are doing in a match you like.','What exercise do you do in a normal week?']::text[]),
 ('CDS-U12-06', 'CDS-U12', 'CDS', 6, 'Team Sports', 'Môn thể thao đồng đội', 'A1', 18, 'Gọi tên được các môn thể thao đồng đội và nói mình thích môn nào.', ARRAY['danh từ chỉ môn thể thao','động từ play']::text[], 'I play … / My favorite sport is …', 'Sáu khung sân đấu: bóng đá, bóng chuyền, bóng rổ, bóng ném, cầu lông đôi và bóng bàn đôi, kèm áo đấu và bảng tỉ số.', ARRAY['What team sport do you like?','Do you play football with your friends?','Which team do you support?']::text[]),
 ('CDS-U12-07', 'CDS-U12', 'CDS', 7, 'Individual Sports', 'Môn thể thao cá nhân', 'A2', 22, 'So sánh được các môn thể thao cá nhân về độ khó và lợi ích cho sức khỏe.', ARRAY['danh từ chỉ môn thể thao','tính từ so sánh hơn']::text[], '… is harder than … for me.', 'Bộ tranh tám môn cá nhân: chạy bộ, đạp xe, bơi, tennis, cầu lông, yoga, cử tạ và võ thuật.', ARRAY['Which individual sport suits you best, and why?','Is it better to exercise alone or with a group? Explain.','What stops people from doing sport regularly?']::text[]),
 ('CDS-U12-08', 'CDS-U12', 'CDS', 8, 'Winter Sports and Water Sports', 'Thể thao mùa đông và dưới nước', 'A2', 22, 'Mô tả được các môn thể thao mùa đông, dưới nước và điều kiện cần có để chơi.', ARRAY['danh từ chỉ môn thể thao','cấu trúc need to / have to']::text[], 'You need … to go …', 'Tranh đôi: sườn núi phủ tuyết với trượt tuyết và trượt băng, bên cạnh là vịnh biển với lướt ván, chèo kayak, lặn ống thở và lướt ván buồm.', ARRAY['Would you like to try skiing or snowboarding? Why?','Which water sport is popular where you live?','What safety rules should people follow in water sports?']::text[]),
 ('CDS-U12-09', 'CDS-U12', 'CDS', 9, 'Sports Equipment', 'Dụng cụ thể thao', 'A1', 20, 'Gọi tên được dụng cụ thể thao và ghép đúng dụng cụ với từng môn.', ARRAY['danh từ đếm được','cấu trúc need a']::text[], 'You need a … to play …', 'Kệ hàng trong cửa hàng thể thao: bóng đá, bóng rổ, vợt cầu lông, mũ bảo hiểm, găng tay, giày chạy, kính bơi, tạ tay và lưới.', ARRAY['What sports equipment do you have?','What do you need to play badminton?','Where do people buy sports things in your town?']::text[]),
 ('CDS-U12-10', 'CDS-U12', 'CDS', 10, 'Hobbies and Games', 'Sở thích và trò chơi', 'A2', 24, 'Nói về sở thích của mình, tần suất thực hiện và lý do yêu thích hoạt động đó.', ARRAY['danh động từ sau enjoy/like','trạng từ chỉ tần suất']::text[], 'I enjoy … I usually do it …', 'Phòng khách cuối tuần: người đan len, người vẽ tranh, bàn cờ vua và cờ tướng, bộ xếp hình, cuốn sưu tập tem và nhóm bạn chơi bài.', ARRAY['What hobby do you spend the most time on?','How did you start your hobby?','Do you prefer board games or video games? Explain why.']::text[]),
 ('CDS-U12-11', 'CDS-U12', 'CDS', 11, 'Electronics and Photography', 'Đồ điện tử và nhiếp ảnh', 'A2', 24, 'Gọi tên được thiết bị điện tử và mô tả cách chụp, lưu, chia sẻ một bức ảnh.', ARRAY['danh từ chỉ thiết bị','động từ chỉ thao tác']::text[], 'I took this photo with my … and shared it on …', 'Bàn trưng bày thiết bị: máy ảnh và ống kính rời, chân máy, điện thoại, tai nghe, loa, tivi, máy tính bảng, thẻ nhớ và sạc dự phòng.', ARRAY['Which electronic device could you not live without, and why?','Do you take many photos? What do you photograph most?','How have phone cameras changed the way people remember their trips?']::text[]),
 ('CDS-U12-12', 'CDS-U12', 'CDS', 12, 'Entertainment', 'Giải trí', 'B1', 24, 'Nêu và bảo vệ được ý kiến của mình về các loại hình giải trí, phim ảnh và âm nhạc.', ARRAY['danh từ chỉ thể loại','tính từ nêu đánh giá']::text[], 'I''d say it''s worth watching because …', 'Đêm giải trí ghép nhiều cảnh: sân khấu ca nhạc, rạp chiếu phim, trường quay chương trình truyền hình, vở kịch và cảnh xem phim trực tuyến tại nhà.', ARRAY['What kind of films or music do you enjoy, and what does that say about you?','Has streaming made cinemas less important? Give your opinion.','Describe a show or a concert that impressed you and explain why.']::text[]),
 ('CDS-U12-13', 'CDS-U12', 'CDS', 13, 'Holidays', 'Ngày lễ', 'A2', 22, 'Giới thiệu được các ngày lễ của Việt Nam và quốc tế cùng phong tục đi kèm.', ARRAY['danh từ chỉ ngày lễ','giới từ chỉ thời gian in/on/at']::text[], 'We celebrate … in … / On …, people usually …', 'Vòng tròn lịch lễ hội: Tết Nguyên đán với bánh chưng và hoa mai, Trung thu với đèn lồng, Quốc khánh với cờ đỏ, Giáng sinh, pháo hoa đêm giao thừa dương lịch và Ngày Quốc tế Lao động.', ARRAY['Which holiday is the most important in your family, and how do you celebrate it?','How is Tet different from New Year''s Day in other countries?','Do you think traditional holidays are changing? In what way?']::text[]),
 ('CDS-U12-14', 'CDS-U12', 'CDS', 14, 'A Party', 'Tiệc tùng', 'A2', 22, 'Mời khách, chuẩn bị và kể lại được một buổi tiệc bằng thì tương lai và quá khứ đơn.', ARRAY['danh từ chỉ đồ dùng tiệc','thì tương lai với be going to']::text[], 'We''re going to have a party. Would you like to come?', 'Tiệc sinh nhật tại nhà: bánh kem cắm nến, bóng bay, dây trang trí, chồng quà, bàn đồ ăn nhẹ và nhóm khách hát karaoke.', ARRAY['Describe a party you enjoyed. What made it special?','What do you need to prepare for a birthday party?','How do people celebrate birthdays in Viet Nam?']::text[])
on conflict (code) do update set
  "unit_code"=excluded."unit_code",
  "curriculum_code"=excluded."curriculum_code",
  "ord"=excluded."ord",
  "name_en"=excluded."name_en",
  "name_vi"=excluded."name_vi",
  "cefr"=excluded."cefr",
  "target_words"=excluded."target_words",
  "objective"=excluded."objective",
  "focus"=excluded."focus",
  "pattern"=excluded."pattern",
  "image_brief"=excluded."image_brief",
  "prompts"=excluded."prompts";

-- ══════════════ 4. KIỂM TRA ══════════════
select (select count(*) from curricula) as so_giao_trinh,
       (select count(*) from curriculum_units where curriculum_code='CDS') as so_nhom,
       (select count(*) from curriculum_topics where curriculum_code='CDS') as so_chu_de;
