-- ═══════════════════════════════════════════════════════════
-- EnglishUp · 04 · Lớp Morphology (hình vị)
-- CHẠY SAU 01_migration.sql + 02_seed_ngsl.sql
--
-- Đây là tầng đòn bẩy: học 1 hình vị -> mở khoá cả cụm từ.
--   port (mang) -> import, export, transport, report, support...
-- ═══════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS morphemes (
  id          SERIAL PRIMARY KEY,
  morpheme    TEXT NOT NULL UNIQUE,
  type        TEXT NOT NULL CHECK (type IN ('prefix','suffix','root')),
  origin      TEXT NOT NULL CHECK (origin IN ('Latin','Greek','Germanic')),
  meaning_vi  TEXT NOT NULL,
  gloss_en    TEXT NOT NULL,
  rank        SMALLINT,
  note        TEXT
);
COMMENT ON TABLE  morphemes        IS 'Tiền tố / hậu tố / gốc từ — 24 prefix + 23 suffix + 60 root';
COMMENT ON COLUMN morphemes.rank   IS 'Thứ tự ưu tiên dạy trong mỗi loại (1 = dạy trước nhất)';

CREATE TABLE IF NOT EXISTS word_morphemes (
  word_id     BIGINT NOT NULL REFERENCES words(id)     ON DELETE CASCADE,
  morpheme_id INT    NOT NULL REFERENCES morphemes(id) ON DELETE CASCADE,
  PRIMARY KEY (word_id, morpheme_id)
);
CREATE INDEX IF NOT EXISTS wm_morpheme_idx ON word_morphemes (morpheme_id);
COMMENT ON TABLE word_morphemes IS
  'Liên kết từ <-> hình vị. Chỉ chứa liên kết ĐÃ DUYỆT TAY: 707 giữ / 1376 ứng viên máy sinh (49% bị loại).';

TRUNCATE word_morphemes, morphemes RESTART IDENTITY CASCADE;

INSERT INTO morphemes (morpheme, type, origin, meaning_vi, gloss_en, rank, note) VALUES
  ('un-', 'prefix', 'Germanic', 'không, phi, đảo ngược', 'not, reverse', 1, 'Tiền tố phổ biến nhất — chiếm 26% mọi từ có tiền tố'),
  ('re-', 'prefix', 'Latin', 'lại, trở lại', 'again, back', 2, NULL),
  ('in-', 'prefix', 'Latin', 'không, phi', 'not', 3, 'Biến thể: im- (trước b/m/p), il- (trước l), ir- (trước r)'),
  ('dis-', 'prefix', 'Latin', 'không, tách ra, đảo ngược', 'not, apart', 4, '4 tiền tố đầu phủ 58% mọi từ có tiền tố'),
  ('en-', 'prefix', 'Latin', 'làm cho, khiến thành', 'make, put into', 5, 'Biến thể: em- trước b/m/p'),
  ('non-', 'prefix', 'Latin', 'không, phi', 'not', 6, NULL),
  ('over-', 'prefix', 'Germanic', 'quá mức, vượt trên', 'too much, above', 7, NULL),
  ('mis-', 'prefix', 'Germanic', 'sai, nhầm', 'wrongly', 8, NULL),
  ('sub-', 'prefix', 'Latin', 'dưới, phụ', 'under, below', 9, NULL),
  ('pre-', 'prefix', 'Latin', 'trước', 'before', 10, NULL),
  ('inter-', 'prefix', 'Latin', 'giữa, liên', 'between, among', 11, NULL),
  ('fore-', 'prefix', 'Germanic', 'trước, phía trước', 'before, front', 12, NULL),
  ('de-', 'prefix', 'Latin', 'bỏ, xuống, ngược lại', 'remove, down', 13, NULL),
  ('trans-', 'prefix', 'Latin', 'xuyên qua, chuyển', 'across, through', 14, NULL),
  ('super-', 'prefix', 'Latin', 'trên, siêu', 'above, beyond', 15, NULL),
  ('semi-', 'prefix', 'Latin', 'nửa, bán', 'half', 16, NULL),
  ('anti-', 'prefix', 'Greek', 'chống, phản', 'against', 17, NULL),
  ('mid-', 'prefix', 'Germanic', 'giữa', 'middle', 18, NULL),
  ('under-', 'prefix', 'Germanic', 'dưới, chưa đủ', 'below, too little', 19, '20 tiền tố đầu phủ 97% mọi từ có tiền tố'),
  ('co-', 'prefix', 'Latin', 'cùng, đồng', 'together', 20, 'Biến thể: com-, con-, col-, cor-'),
  ('ex-', 'prefix', 'Latin', 'ra ngoài, cựu', 'out of, former', 21, NULL),
  ('pro-', 'prefix', 'Latin', 'ủng hộ, phía trước', 'forward, in favor', 22, NULL),
  ('auto-', 'prefix', 'Greek', 'tự, tự động', 'self', 23, NULL),
  ('multi-', 'prefix', 'Latin', 'nhiều, đa', 'many', 24, NULL),
  ('-s', 'suffix', 'Germanic', 'số nhiều; ngôi 3 số ít', 'plural; 3rd person', 1, 'Hình vị biến hình'),
  ('-ed', 'suffix', 'Germanic', 'thì quá khứ; quá khứ phân từ', 'past tense', 2, 'Hình vị biến hình'),
  ('-ing', 'suffix', 'Germanic', 'đang; danh động từ', 'progressive, gerund', 3, 'Hình vị biến hình'),
  ('-er', 'suffix', 'Germanic', 'người/vật làm việc gì; hơn', 'agent; comparative', 4, 'CHÍNH LÀ CỤM ER TRONG VIDEO — teach→teacher, work→worker'),
  ('-est', 'suffix', 'Germanic', 'nhất', 'superlative', 5, NULL),
  ('-ly', 'suffix', 'Germanic', 'một cách…', 'in manner of', 6, 'Biến tính từ thành trạng từ'),
  ('-tion', 'suffix', 'Latin', 'sự, việc, quá trình', 'act, state', 7, 'Biến thể: -sion, -ation'),
  ('-ness', 'suffix', 'Germanic', 'sự, tính, trạng thái', 'state, quality', 8, 'Biến tính từ thành danh từ'),
  ('-ment', 'suffix', 'Latin', 'sự, kết quả của việc', 'result, action', 9, NULL),
  ('-able', 'suffix', 'Latin', 'có thể … được', 'capable of', 10, 'Biến thể: -ible'),
  ('-ful', 'suffix', 'Germanic', 'đầy, nhiều', 'full of', 11, NULL),
  ('-less', 'suffix', 'Germanic', 'không có, thiếu', 'without', 12, NULL),
  ('-ity', 'suffix', 'Latin', 'tính, sự', 'state, quality', 13, NULL),
  ('-ous', 'suffix', 'Latin', 'có tính chất, đầy', 'full of, having', 14, NULL),
  ('-al', 'suffix', 'Latin', 'thuộc về', 'relating to', 15, NULL),
  ('-ive', 'suffix', 'Latin', 'có xu hướng, mang tính', 'tending to', 16, NULL),
  ('-ist', 'suffix', 'Greek', 'người theo/làm', 'one who', 17, NULL),
  ('-ism', 'suffix', 'Greek', 'chủ nghĩa, học thuyết', 'doctrine', 18, NULL),
  ('-ize', 'suffix', 'Greek', 'làm cho thành', 'make into', 19, 'Biến thể Anh-Anh: -ise'),
  ('-ic', 'suffix', 'Greek', 'thuộc về, có tính', 'relating to', 20, NULL),
  ('-y', 'suffix', 'Germanic', 'có tính chất', 'characterized by', 21, NULL),
  ('-ship', 'suffix', 'Germanic', 'trạng thái, chức vị', 'state, position', 22, NULL),
  ('-hood', 'suffix', 'Germanic', 'thời kỳ, trạng thái', 'state, period', 23, NULL),
  ('port', 'root', 'Latin', 'mang, chở', 'carry', 1, 'import, export, transport, portable, support, report'),
  ('spect', 'root', 'Latin', 'nhìn', 'look', 2, 'inspect, respect, expect, aspect, spectator'),
  ('dict', 'root', 'Latin', 'nói', 'say, speak', 3, 'predict, dictionary, contradict, dictate'),
  ('duc', 'root', 'Latin', 'dẫn, dắt', 'lead', 4, 'produce, reduce, introduce, conduct — biến thể: duct'),
  ('ject', 'root', 'Latin', 'ném, quăng', 'throw', 5, 'project, reject, inject, object, subject'),
  ('scrib', 'root', 'Latin', 'viết', 'write', 6, 'describe, prescribe, subscribe — biến thể: script'),
  ('mit', 'root', 'Latin', 'gửi, phái', 'send', 7, 'submit, permit, transmit, admit — biến thể: miss'),
  ('tract', 'root', 'Latin', 'kéo', 'pull, drag', 8, 'attract, extract, contract, tractor'),
  ('fer', 'root', 'Latin', 'mang, đem', 'carry, bear', 9, 'transfer, refer, prefer, offer, differ'),
  ('pos', 'root', 'Latin', 'đặt, để', 'put, place', 10, 'position, compose, expose, deposit, purpose'),
  ('ven', 'root', 'Latin', 'đến', 'come', 11, 'convene, prevent, invent, event — biến thể: vent'),
  ('tend', 'root', 'Latin', 'căng, kéo dài', 'stretch', 12, 'extend, attend, intend, pretend'),
  ('cede', 'root', 'Latin', 'đi, nhường', 'go, yield', 13, 'proceed, precede, exceed — biến thể: ceed, cess'),
  ('form', 'root', 'Latin', 'hình dạng', 'shape', 14, 'reform, transform, uniform, formal, inform'),
  ('struct', 'root', 'Latin', 'xây dựng', 'build', 15, 'construct, instruct, structure, destroy'),
  ('vis', 'root', 'Latin', 'nhìn thấy', 'see', 16, 'vision, visible, television, revise — biến thể: vid'),
  ('aud', 'root', 'Latin', 'nghe', 'hear', 17, 'audio, audience, audible, auditorium'),
  ('graph', 'root', 'Greek', 'viết, vẽ', 'write, draw', 18, 'photograph, paragraph, graphic — biến thể: gram'),
  ('phon', 'root', 'Greek', 'âm thanh', 'sound', 19, 'telephone, symphony, phonics, microphone'),
  ('tele', 'root', 'Greek', 'xa', 'far', 20, 'telephone, television, telescope'),
  ('scope', 'root', 'Greek', 'xem, quan sát', 'watch, view', 21, 'microscope, telescope'),
  ('micro', 'root', 'Greek', 'nhỏ, vi', 'small', 22, 'microscope, microphone, microwave'),
  ('bio', 'root', 'Greek', 'sự sống', 'life', 23, 'biology, biography, antibiotic'),
  ('geo', 'root', 'Greek', 'đất, trái đất', 'earth', 24, 'geography, geology, geometry'),
  ('log', 'root', 'Greek', 'lời, học thuyết', 'word, study', 25, 'logic, dialogue, biology, apology'),
  ('therm', 'root', 'Greek', 'nhiệt', 'heat', 26, 'thermometer, thermal'),
  ('meter', 'root', 'Greek', 'đo', 'measure', 27, 'thermometer, diameter, kilometer — biến thể: metr'),
  ('photo', 'root', 'Greek', 'ánh sáng', 'light', 28, 'photograph, photocopy'),
  ('chron', 'root', 'Greek', 'thời gian', 'time', 29, 'chronic, synchronize, chronology'),
  ('psych', 'root', 'Greek', 'tâm trí, tinh thần', 'mind, soul', 30, 'psychology, psychiatric'),
  ('man', 'root', 'Latin', 'tay', 'hand', 31, 'manual, manage, manufacture, manuscript'),
  ('ped', 'root', 'Latin', 'chân', 'foot', 32, 'pedal, pedestrian — chú ý: ped Hy Lạp nghĩa là trẻ em'),
  ('cap', 'root', 'Latin', 'đầu; nắm giữ', 'head; take', 33, 'capital, captain, capture, capable — biến thể: cept'),
  ('cred', 'root', 'Latin', 'tin', 'believe', 34, 'credit, incredible, credible'),
  ('mem', 'root', 'Latin', 'nhớ', 'remember', 35, 'memory, memorial, remember'),
  ('mob', 'root', 'Latin', 'chuyển động', 'move', 36, 'mobile, automobile — biến thể: mot, mov'),
  ('vac', 'root', 'Latin', 'trống, rỗng', 'empty', 37, 'vacant, vacation, vacuum'),
  ('vit', 'root', 'Latin', 'sự sống', 'life', 38, 'vital, vitamin, survive — biến thể: viv'),
  ('nat', 'root', 'Latin', 'sinh ra', 'born', 39, 'nature, native, national, innate'),
  ('mort', 'root', 'Latin', 'chết', 'death', 40, 'mortal, mortgage'),
  ('sens', 'root', 'Latin', 'cảm nhận', 'feel', 41, 'sense, sensitive, sensation — biến thể: sent'),
  ('voc', 'root', 'Latin', 'gọi, tiếng nói', 'call, voice', 42, 'vocal, vocabulary, invoke — biến thể: vok'),
  ('sci', 'root', 'Latin', 'biết', 'know', 43, 'science, conscious, conscience'),
  ('cogn', 'root', 'Latin', 'biết, nhận ra', 'know', 44, 'recognize, cognitive'),
  ('fac', 'root', 'Latin', 'làm, tạo', 'make, do', 45, 'factory, manufacture, benefit — biến thể: fect, fic'),
  ('jud', 'root', 'Latin', 'xét xử', 'judge', 46, 'judge, judicial, prejudice'),
  ('leg', 'root', 'Latin', 'luật; đọc', 'law; read', 47, 'legal, legislation, legible'),
  ('liber', 'root', 'Latin', 'tự do', 'free', 48, 'liberty, liberal, deliver'),
  ('loc', 'root', 'Latin', 'nơi chốn', 'place', 49, 'local, location, allocate'),
  ('mag', 'root', 'Latin', 'lớn', 'great', 50, 'magnify, magnificent, major — biến thể: magn, maj'),
  ('pel', 'root', 'Latin', 'đẩy', 'push, drive', 51, 'propel, expel, compel — biến thể: puls'),
  ('plic', 'root', 'Latin', 'gấp, xếp', 'fold', 52, 'complicate, application, duplicate — biến thể: ply'),
  ('reg', 'root', 'Latin', 'cai trị, quy tắc', 'rule', 53, 'regular, regulate, regime'),
  ('rupt', 'root', 'Latin', 'vỡ, gãy', 'break', 54, 'interrupt, corrupt, erupt, bankrupt'),
  ('sequ', 'root', 'Latin', 'theo sau', 'follow', 55, 'sequence, consequence — biến thể: secu'),
  ('spir', 'root', 'Latin', 'thở', 'breathe', 56, 'inspire, respiratory, spirit'),
  ('sta', 'root', 'Latin', 'đứng', 'stand', 57, 'stable, station, status, statue — biến thể: stat'),
  ('tang', 'root', 'Latin', 'chạm', 'touch', 58, 'contact, tangible — biến thể: tact, ting'),
  ('term', 'root', 'Latin', 'giới hạn, kết thúc', 'end, limit', 59, 'terminal, determine, terminate'),
  ('vert', 'root', 'Latin', 'quay, xoay', 'turn', 60, 'convert, reverse, advertise — biến thể: vers');

-- Liên kết (khớp theo lower(term), an toàn nếu DB viết hoa khác)

INSERT INTO word_morphemes (word_id, morpheme_id)
SELECT w.id, m.id
FROM (VALUES
  ('common', 'co-'),
  ('contact', 'co-'),
  ('compare', 'co-'),
  ('contract', 'co-'),
  ('competition', 'co-'),
  ('complex', 'co-'),
  ('context', 'co-'),
  ('contribute', 'co-'),
  ('combine', 'co-'),
  ('colleague', 'co-'),
  ('concert', 'co-'),
  ('compete', 'co-'),
  ('confuse', 'co-'),
  ('contemporary', 'co-'),
  ('compound', 'co-'),
  ('correspond', 'co-'),
  ('compromise', 'co-'),
  ('contest', 'co-'),
  ('compose', 'co-'),
  ('cooperation', 'co-'),
  ('composition', 'co-'),
  ('confusion', 'co-'),
  ('comprise', 'co-'),
  ('describe', 'de-'),
  ('decline', 'de-'),
  ('decrease', 'de-'),
  ('deposit', 'de-'),
  ('depress', 'de-'),
  ('disease', 'dis-'),
  ('discover', 'dis-'),
  ('discount', 'dis-'),
  ('disappear', 'dis-'),
  ('distribute', 'dis-'),
  ('disorder', 'dis-'),
  ('dismiss', 'dis-'),
  ('disagree', 'dis-'),
  ('distant', 'dis-'),
  ('enjoy', 'en-'),
  ('encourage', 'en-'),
  ('ensure', 'en-'),
  ('enable', 'en-'),
  ('entitle', 'en-'),
  ('explain', 'ex-'),
  ('express', 'ex-'),
  ('extend', 'ex-'),
  ('exchange', 'ex-'),
  ('expensive', 'ex-'),
  ('extent', 'ex-'),
  ('expense', 'ex-'),
  ('export', 'ex-'),
  ('expose', 'ex-'),
  ('extension', 'ex-'),
  ('extract', 'ex-'),
  ('forecast', 'fore-'),
  ('independent', 'in-'),
  ('impossible', 'in-'),
  ('immediate', 'in-'),
  ('independence', 'in-'),
  ('illegal', 'in-'),
  ('international', 'inter-'),
  ('interview', 'inter-'),
  ('interaction', 'inter-'),
  ('mistake', 'mis-'),
  ('overall', 'over-'),
  ('overcome', 'over-'),
  ('overseas', 'over-'),
  ('prepare', 'pre-'),
  ('prefer', 'pre-'),
  ('prevent', 'pre-'),
  ('premise', 'pre-'),
  ('preference', 'pre-'),
  ('program', 'pro-'),
  ('product', 'pro-'),
  ('produce', 'pro-'),
  ('propose', 'pro-'),
  ('progress', 'pro-'),
  ('promote', 'pro-'),
  ('promotion', 'pro-'),
  ('report', 're-'),
  ('return', 're-'),
  ('record', 're-'),
  ('remember', 're-'),
  ('research', 're-'),
  ('represent', 're-'),
  ('review', 're-'),
  ('replace', 're-'),
  ('reply', 're-'),
  ('reform', 're-'),
  ('reaction', 're-'),
  ('repeat', 're-'),
  ('recall', 're-'),
  ('remind', 're-'),
  ('recover', 're-'),
  ('researcher', 're-'),
  ('reserve', 're-'),
  ('reporter', 're-'),
  ('recognition', 're-'),
  ('representation', 're-'),
  ('restore', 're-'),
  ('reverse', 're-'),
  ('react', 're-'),
  ('revise', 're-'),
  ('submit', 'sub-'),
  ('transfer', 'trans-'),
  ('transport', 'trans-'),
  ('transform', 'trans-'),
  ('translate', 'trans-'),
  ('unclear', 'un-'),
  ('unfortunately', 'un-'),
  ('unable', 'un-'),
  ('unlike', 'un-'),
  ('unusual', 'un-'),
  ('unemployment', 'un-'),
  ('unlikely', 'un-'),
  ('unknown', 'un-'),
  ('uncertainty', 'un-'),
  ('underlie', 'under-'),
  ('audience', 'aud'),
  ('biological', 'bio'),
  ('capital', 'cap'),
  ('capacity', 'cap'),
  ('capture', 'cap'),
  ('capable', 'cap'),
  ('capability', 'cap'),
  ('recognize', 'cogn'),
  ('recognition', 'cogn'),
  ('credit', 'cred'),
  ('predict', 'dict'),
  ('product', 'duc'),
  ('produce', 'duc'),
  ('education', 'duc'),
  ('reduce', 'duc'),
  ('production', 'duc'),
  ('introduce', 'duc'),
  ('conduct', 'duc'),
  ('introduction', 'duc'),
  ('reduction', 'duc'),
  ('producer', 'duc'),
  ('educational', 'duc'),
  ('educate', 'duc'),
  ('fact', 'fac'),
  ('factor', 'fac'),
  ('manufacture', 'fac'),
  ('factory', 'fac'),
  ('manufacturer', 'fac'),
  ('satisfaction', 'fac'),
  ('different', 'fer'),
  ('offer', 'fer'),
  ('difference', 'fer'),
  ('suffer', 'fer'),
  ('refer', 'fer'),
  ('reference', 'fer'),
  ('prefer', 'fer'),
  ('transfer', 'fer'),
  ('differ', 'fer'),
  ('preference', 'fer'),
  ('differently', 'fer'),
  ('information', 'form'),
  ('inform', 'form'),
  ('reform', 'form'),
  ('formal', 'form'),
  ('uniform', 'form'),
  ('formula', 'form'),
  ('platform', 'form'),
  ('transform', 'form'),
  ('formation', 'form'),
  ('format', 'form'),
  ('photograph', 'graph'),
  ('paragraph', 'graph'),
  ('subject', 'ject'),
  ('project', 'ject'),
  ('object', 'ject'),
  ('objective', 'ject'),
  ('reject', 'ject'),
  ('judge', 'jud'),
  ('judgment', 'jud'),
  ('legal', 'leg'),
  ('legislation', 'leg'),
  ('illegal', 'leg'),
  ('privilege', 'leg'),
  ('liberal', 'liber'),
  ('local', 'loc'),
  ('location', 'loc'),
  ('locate', 'loc'),
  ('technology', 'log'),
  ('apologize', 'log'),
  ('dialog', 'log'),
  ('psychological', 'log'),
  ('biological', 'log'),
  ('logic', 'log'),
  ('manage', 'man'),
  ('manager', 'man'),
  ('management', 'man'),
  ('manufacture', 'man'),
  ('manufacturer', 'man'),
  ('remember', 'mem'),
  ('memory', 'mem'),
  ('admit', 'mit'),
  ('commit', 'mit'),
  ('commitment', 'mit'),
  ('permit', 'mit'),
  ('submit', 'mit'),
  ('mobile', 'mob'),
  ('national', 'nat'),
  ('international', 'nat'),
  ('nature', 'nat'),
  ('nation', 'nat'),
  ('natural', 'nat'),
  ('native', 'nat'),
  ('naturally', 'nat'),
  ('phone', 'phon'),
  ('telephone', 'phon'),
  ('photograph', 'photo'),
  ('complicate', 'plic'),
  ('implication', 'plic'),
  ('report', 'port'),
  ('important', 'port'),
  ('support', 'port'),
  ('importance', 'port'),
  ('transport', 'port'),
  ('export', 'port'),
  ('import', 'port'),
  ('reporter', 'port'),
  ('supporter', 'port'),
  ('transportation', 'port'),
  ('position', 'pos'),
  ('suppose', 'pos'),
  ('purpose', 'pos'),
  ('propose', 'pos'),
  ('post', 'pos'),
  ('proposal', 'pos'),
  ('opposite', 'pos'),
  ('oppose', 'pos'),
  ('opposition', 'pos'),
  ('impose', 'pos'),
  ('expose', 'pos'),
  ('pose', 'pos'),
  ('exposure', 'pos'),
  ('deposit', 'pos'),
  ('compose', 'pos'),
  ('composition', 'pos'),
  ('psychological', 'psych'),
  ('region', 'reg'),
  ('regular', 'reg'),
  ('regulation', 'reg'),
  ('regional', 'reg'),
  ('regularly', 'reg'),
  ('regulate', 'reg'),
  ('science', 'sci'),
  ('scientist', 'sci')
) AS v(term, morph)
JOIN words     w ON lower(w.term) = lower(v.term)
JOIN morphemes m ON m.morpheme    = v.morph
ON CONFLICT DO NOTHING;

INSERT INTO word_morphemes (word_id, morpheme_id)
SELECT w.id, m.id
FROM (VALUES
  ('scientific', 'sci'),
  ('describe', 'scrib'),
  ('sense', 'sens'),
  ('sensitive', 'sens'),
  ('consequence', 'sequ'),
  ('sequence', 'sequ'),
  ('subsequent', 'sequ'),
  ('consequently', 'sequ'),
  ('subsequently', 'sequ'),
  ('respect', 'spect'),
  ('suspect', 'spect'),
  ('perspective', 'spect'),
  ('prospect', 'spect'),
  ('spirit', 'spir'),
  ('inspire', 'spir'),
  ('state', 'sta'),
  ('stand', 'sta'),
  ('stay', 'sta'),
  ('standard', 'sta'),
  ('stage', 'sta'),
  ('establish', 'sta'),
  ('station', 'sta'),
  ('status', 'sta'),
  ('distance', 'sta'),
  ('circumstance', 'sta'),
  ('constant', 'sta'),
  ('assistant', 'sta'),
  ('stable', 'sta'),
  ('substantial', 'sta'),
  ('assistance', 'sta'),
  ('constantly', 'sta'),
  ('substance', 'sta'),
  ('resistance', 'sta'),
  ('establishment', 'sta'),
  ('stability', 'sta'),
  ('distant', 'sta'),
  ('structure', 'struct'),
  ('construction', 'struct'),
  ('instruction', 'struct'),
  ('construct', 'struct'),
  ('destruction', 'struct'),
  ('structural', 'struct'),
  ('television', 'tele'),
  ('telephone', 'tele'),
  ('attend', 'tend'),
  ('extend', 'tend'),
  ('intend', 'tend'),
  ('tendency', 'tend'),
  ('pretend', 'tend'),
  ('attendance', 'tend'),
  ('determine', 'term'),
  ('determination', 'term'),
  ('contract', 'tract'),
  ('attract', 'tract'),
  ('attractive', 'tract'),
  ('extract', 'tract'),
  ('attraction', 'tract'),
  ('abstract', 'tract'),
  ('event', 'ven'),
  ('prevent', 'ven'),
  ('eventually', 'ven'),
  ('revenue', 'ven'),
  ('convention', 'ven'),
  ('intervention', 'ven'),
  ('conventional', 'ven'),
  ('invent', 'ven'),
  ('adventure', 'ven'),
  ('advertise', 'vert'),
  ('advertisement', 'vert'),
  ('convert', 'vert'),
  ('visit', 'vis'),
  ('television', 'vis'),
  ('visitor', 'vis'),
  ('provision', 'vis'),
  ('vision', 'vis'),
  ('advise', 'vis'),
  ('adviser', 'vis'),
  ('visual', 'vis'),
  ('visible', 'vis'),
  ('revise', 'vis'),
  ('vital', 'vit'),
  ('advocate', 'voc'),
  ('available', '-able'),
  ('responsible', '-able'),
  ('comfortable', '-able'),
  ('reasonable', '-able'),
  ('suitable', '-able'),
  ('considerable', '-able'),
  ('variable', '-able'),
  ('capable', '-able'),
  ('valuable', '-able'),
  ('remarkable', '-able'),
  ('visible', '-able'),
  ('acceptable', '-able'),
  ('reliable', '-able'),
  ('flexible', '-able'),
  ('local', '-al'),
  ('political', '-al'),
  ('national', '-al'),
  ('personal', '-al'),
  ('final', '-al'),
  ('natural', '-al'),
  ('normal', '-al'),
  ('central', '-al'),
  ('professional', '-al'),
  ('original', '-al'),
  ('legal', '-al'),
  ('proposal', '-al'),
  ('traditional', '-al'),
  ('medical', '-al'),
  ('trial', '-al'),
  ('additional', '-al'),
  ('federal', '-al'),
  ('global', '-al'),
  ('cultural', '-al'),
  ('critical', '-al'),
  ('environmental', '-al'),
  ('historical', '-al'),
  ('technical', '-al'),
  ('industrial', '-al'),
  ('signal', '-al'),
  ('internal', '-al'),
  ('practical', '-al'),
  ('musical', '-al'),
  ('mental', '-al'),
  ('ideal', '-al'),
  ('formal', '-al'),
  ('regional', '-al'),
  ('emotional', '-al'),
  ('educational', '-al'),
  ('arrival', '-al'),
  ('agricultural', '-al'),
  ('festival', '-al'),
  ('radical', '-al'),
  ('approval', '-al'),
  ('conventional', '-al'),
  ('digital', '-al'),
  ('universal', '-al'),
  ('clinical', '-al'),
  ('survival', '-al'),
  ('classical', '-al'),
  ('biological', '-al'),
  ('experimental', '-al'),
  ('institutional', '-al'),
  ('functional', '-al'),
  ('structural', '-al'),
  ('computer', '-er'),
  ('customer', '-er'),
  ('teacher', '-er'),
  ('leader', '-er'),
  ('manager', '-er'),
  ('worker', '-er'),
  ('player', '-er'),
  ('officer', '-er'),
  ('writer', '-er'),
  ('consumer', '-er'),
  ('reader', '-er'),
  ('driver', '-er'),
  ('speaker', '-er'),
  ('owner', '-er'),
  ('engineer', '-er'),
  ('farmer', '-er'),
  ('researcher', '-er'),
  ('employer', '-er'),
  ('voter', '-er'),
  ('producer', '-er'),
  ('manufacturer', '-er'),
  ('reporter', '-er'),
  ('winner', '-er'),
  ('upper', '-er'),
  ('layer', '-er'),
  ('prisoner', '-er'),
  ('supporter', '-er'),
  ('designer', '-er'),
  ('singer', '-er'),
  ('adviser', '-er'),
  ('inner', '-er'),
  ('dealer', '-er'),
  ('teenager', '-er'),
  ('counter', '-er'),
  ('buyer', '-er'),
  ('publisher', '-er'),
  ('maker', '-er'),
  ('printer', '-er'),
  ('lover', '-er'),
  ('stranger', '-er'),
  ('server', '-er'),
  ('listener', '-er'),
  ('holder', '-er'),
  ('successful', '-ful'),
  ('useful', '-ful'),
  ('wonderful', '-ful'),
  ('powerful', '-ful'),
  ('careful', '-ful'),
  ('helpful', '-ful'),
  ('neighborhood', '-hood'),
  ('childhood', '-hood'),
  ('economic', '-ic'),
  ('basic', '-ic'),
  ('electronic', '-ic'),
  ('academic', '-ic'),
  ('classic', '-ic'),
  ('genetic', '-ic'),
  ('historic', '-ic'),
  ('democratic', '-ic'),
  ('organic', '-ic'),
  ('criticism', '-ism'),
  ('tourism', '-ism'),
  ('artist', '-ist'),
  ('tourist', '-ist'),
  ('journalist', '-ist'),
  ('specialist', '-ist'),
  ('terrorist', '-ist'),
  ('activity', '-ity'),
  ('community', '-ity'),
  ('opportunity', '-ity'),
  ('security', '-ity'),
  ('majority', '-ity'),
  ('reality', '-ity'),
  ('identity', '-ity'),
  ('personality', '-ity'),
  ('priority', '-ity'),
  ('minority', '-ity'),
  ('electricity', '-ity'),
  ('diversity', '-ity'),
  ('stability', '-ity'),
  ('complexity', '-ity'),
  ('density', '-ity'),
  ('effective', '-ive'),
  ('executive', '-ive'),
  ('expensive', '-ive'),
  ('negative', '-ive'),
  ('relative', '-ive'),
  ('alternative', '-ive'),
  ('active', '-ive'),
  ('objective', '-ive'),
  ('native', '-ive'),
  ('attractive', '-ive'),
  ('initiative', '-ive'),
  ('massive', '-ive'),
  ('creative', '-ive'),
  ('impressive', '-ive'),
  ('aggressive', '-ive'),
  ('narrative', '-ive'),
  ('realize', '-ize'),
  ('organize', '-ize'),
  ('criticize', '-ize'),
  ('apologize', '-ize'),
  ('characterize', '-ize'),
  ('specialize', '-ize')
) AS v(term, morph)
JOIN words     w ON lower(w.term) = lower(v.term)
JOIN morphemes m ON m.morpheme    = v.morph
ON CONFLICT DO NOTHING;

INSERT INTO word_morphemes (word_id, morpheme_id)
SELECT w.id, m.id
FROM (VALUES
  ('summarize', '-ize'),
  ('regardless', '-less'),
  ('really', '-ly'),
  ('actually', '-ly'),
  ('especially', '-ly'),
  ('finally', '-ly'),
  ('likely', '-ly'),
  ('certainly', '-ly'),
  ('usually', '-ly'),
  ('particularly', '-ly'),
  ('recently', '-ly'),
  ('exactly', '-ly'),
  ('clearly', '-ly'),
  ('nearly', '-ly'),
  ('quickly', '-ly'),
  ('generally', '-ly'),
  ('obviously', '-ly'),
  ('daily', '-ly'),
  ('completely', '-ly'),
  ('immediately', '-ly'),
  ('suddenly', '-ly'),
  ('directly', '-ly'),
  ('highly', '-ly'),
  ('absolutely', '-ly'),
  ('slightly', '-ly'),
  ('eventually', '-ly'),
  ('extremely', '-ly'),
  ('unfortunately', '-ly'),
  ('apparently', '-ly'),
  ('mostly', '-ly'),
  ('currently', '-ly'),
  ('relatively', '-ly'),
  ('carefully', '-ly'),
  ('totally', '-ly'),
  ('normally', '-ly'),
  ('mainly', '-ly'),
  ('fairly', '-ly'),
  ('slowly', '-ly'),
  ('friendly', '-ly'),
  ('entirely', '-ly'),
  ('strongly', '-ly'),
  ('definitely', '-ly'),
  ('previously', '-ly'),
  ('largely', '-ly'),
  ('seriously', '-ly'),
  ('lovely', '-ly'),
  ('increasingly', '-ly'),
  ('significantly', '-ly'),
  ('surely', '-ly'),
  ('frequently', '-ly'),
  ('properly', '-ly'),
  ('closely', '-ly'),
  ('widely', '-ly'),
  ('equally', '-ly'),
  ('merely', '-ly'),
  ('truly', '-ly'),
  ('effectively', '-ly'),
  ('perfectly', '-ly'),
  ('personally', '-ly'),
  ('approximately', '-ly'),
  ('partly', '-ly'),
  ('originally', '-ly'),
  ('secondly', '-ly'),
  ('rapidly', '-ly'),
  ('typically', '-ly'),
  ('deeply', '-ly'),
  ('respectively', '-ly'),
  ('ultimately', '-ly'),
  ('unlikely', '-ly'),
  ('elderly', '-ly'),
  ('virtually', '-ly'),
  ('naturally', '-ly'),
  ('initially', '-ly'),
  ('rarely', '-ly'),
  ('constantly', '-ly'),
  ('badly', '-ly'),
  ('gradually', '-ly'),
  ('similarly', '-ly'),
  ('regularly', '-ly'),
  ('briefly', '-ly'),
  ('newly', '-ly'),
  ('occasionally', '-ly'),
  ('precisely', '-ly'),
  ('greatly', '-ly'),
  ('successfully', '-ly'),
  ('roughly', '-ly'),
  ('literally', '-ly'),
  ('consequently', '-ly'),
  ('potentially', '-ly'),
  ('hopefully', '-ly'),
  ('firmly', '-ly'),
  ('surprisingly', '-ly'),
  ('differently', '-ly'),
  ('weekly', '-ly'),
  ('firstly', '-ly'),
  ('quietly', '-ly'),
  ('monthly', '-ly'),
  ('subsequently', '-ly'),
  ('gently', '-ly'),
  ('faithfully', '-ly'),
  ('government', '-ment'),
  ('development', '-ment'),
  ('management', '-ment'),
  ('statement', '-ment'),
  ('agreement', '-ment'),
  ('movement', '-ment'),
  ('treatment', '-ment'),
  ('investment', '-ment'),
  ('argument', '-ment'),
  ('equipment', '-ment'),
  ('requirement', '-ment'),
  ('improvement', '-ment'),
  ('payment', '-ment'),
  ('arrangement', '-ment'),
  ('assessment', '-ment'),
  ('commitment', '-ment'),
  ('judgment', '-ment'),
  ('employment', '-ment'),
  ('settlement', '-ment'),
  ('appointment', '-ment'),
  ('advertisement', '-ment'),
  ('unemployment', '-ment'),
  ('achievement', '-ment'),
  ('retirement', '-ment'),
  ('entertainment', '-ment'),
  ('involvement', '-ment'),
  ('establishment', '-ment'),
  ('measurement', '-ment'),
  ('announcement', '-ment'),
  ('amendment', '-ment'),
  ('adjustment', '-ment'),
  ('excitement', '-ment'),
  ('attachment', '-ment'),
  ('illness', '-ness'),
  ('awareness', '-ness'),
  ('weakness', '-ness'),
  ('darkness', '-ness'),
  ('various', '-ous'),
  ('famous', '-ous'),
  ('dangerous', '-ous'),
  ('nervous', '-ous'),
  ('continuous', '-ous'),
  ('relationship', '-ship'),
  ('leadership', '-ship'),
  ('membership', '-ship'),
  ('friendship', '-ship'),
  ('partnership', '-ship'),
  ('championship', '-ship'),
  ('ownership', '-ship'),
  ('information', '-tion'),
  ('organization', '-tion'),
  ('addition', '-tion'),
  ('production', '-tion'),
  ('discussion', '-tion'),
  ('relation', '-tion'),
  ('operation', '-tion'),
  ('conversation', '-tion'),
  ('generation', '-tion'),
  ('introduction', '-tion'),
  ('consideration', '-tion'),
  ('location', '-tion'),
  ('regulation', '-tion'),
  ('division', '-tion'),
  ('recommendation', '-tion'),
  ('combination', '-tion'),
  ('expectation', '-tion'),
  ('presentation', '-tion'),
  ('reduction', '-tion'),
  ('reputation', '-tion'),
  ('observation', '-tion'),
  ('corporation', '-tion'),
  ('creation', '-tion'),
  ('convention', '-tion'),
  ('examination', '-tion'),
  ('interpretation', '-tion'),
  ('variation', '-tion'),
  ('representation', '-tion'),
  ('preparation', '-tion'),
  ('edition', '-tion'),
  ('publication', '-tion'),
  ('obligation', '-tion'),
  ('foundation', '-tion'),
  ('invitation', '-tion'),
  ('intervention', '-tion'),
  ('formation', '-tion'),
  ('promotion', '-tion'),
  ('celebration', '-tion'),
  ('imagination', '-tion'),
  ('possession', '-tion'),
  ('abortion', '-tion'),
  ('limitation', '-tion'),
  ('indication', '-tion'),
  ('cooperation', '-tion'),
  ('motivation', '-tion'),
  ('implementation', '-tion'),
  ('determination', '-tion'),
  ('transportation', '-tion'),
  ('registration', '-tion'),
  ('difficulty', '-y'),
  ('funny', '-y'),
  ('healthy', '-y'),
  ('angry', '-y'),
  ('lucky', '-y'),
  ('guilty', '-y'),
  ('dirty', '-y'),
  ('bloody', '-y'),
  ('wealthy', '-y')
) AS v(term, morph)
JOIN words     w ON lower(w.term) = lower(v.term)
JOIN morphemes m ON m.morpheme    = v.morph
ON CONFLICT DO NOTHING;

-- ─── View: cây từ theo hình vị ───────────────────────────────
CREATE OR REPLACE VIEW morpheme_tree AS
SELECT m.morpheme, m.type, m.origin, m.meaning_vi,
       count(w.id)                        AS so_tu,
       array_agg(w.term ORDER BY w.ngsl_rank) AS cac_tu
FROM morphemes m
JOIN word_morphemes wm ON wm.morpheme_id = m.id
JOIN words w           ON w.id = wm.word_id
GROUP BY m.id, m.morpheme, m.type, m.origin, m.meaning_vi;

-- ─── Kiểm tra ────────────────────────────────────────────────
-- SELECT count(*) FROM morphemes;       -- 107
-- SELECT count(*) FROM word_morphemes;  -- 707
-- SELECT * FROM morpheme_tree WHERE morpheme = 'port';
-- Hình vị nào đáng dạy trước (mở khoá nhiều từ nhất):
-- SELECT morpheme, meaning_vi, so_tu FROM morpheme_tree ORDER BY so_tu DESC LIMIT 20;
