-- ═══════════════════════════════════════════════════════════
-- EnglishUp · 06 · Sổ từ tự bấm tra  (BẢN ĐÚNG — thay cho 05_family.sql)
--
-- Vì sao có file này: 05_family.sql tạo bảng `profiles` riêng, không mật khẩu.
-- Sai. EnglishUp ĐÃ CÓ Supabase Auth thật (accounts/register/tai-khoan +
-- user_profiles + topbar.js). File này gắn thẳng vào auth.users,
-- theo đúng pattern của video_progress trong migration_video.sql.
--
-- ĐỪNG chạy 05_family.sql. Chạy file này.
-- Cần chạy trước: 01_migration.sql (thêm cột NGSL vào words)
-- ═══════════════════════════════════════════════════════════

create table if not exists public.saved_words (
  id            bigint generated by default as identity primary key,
  user_id       uuid not null references auth.users(id) on delete cascade,
  term          text not null,
  phonetic      text,
  definition_vi text,
  topic         text,
  source        text,          -- gặp ở đâu: 'video:<title>' | 'noi' | 'game'
  context       text,          -- câu chứa từ lúc bấm tra
  word_id       bigint references public.words(id) on delete set null,

  -- SRS bậc thang cố định 1·3·7·14·30·60·120
  -- Kim & Webb (2022, meta-analysis 48 thí nghiệm): equal ≈ expanding spacing,
  -- không khác biệt thống kê -> không cần SM-2 ở đây.
  -- (flashcard.html vẫn dùng SM-2 trên srs_cards — hai hệ độc lập, không đụng nhau.)
  step          smallint not null default -1,
  due           date     not null default current_date,
  reps          smallint not null default 0,
  lapses        smallint not null default 0,
  created_at    timestamptz not null default now(),
  unique (user_id, term)
);

create index if not exists sw_due_idx   on public.saved_words (user_id, due);
create index if not exists sw_topic_idx on public.saved_words (user_id, topic);

-- RLS bật, mỗi người chỉ thấy sổ của mình — giống video_progress
alter table public.saved_words enable row level security;
drop policy if exists "own saved words" on public.saved_words;
create policy "own saved words" on public.saved_words
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

comment on table public.saved_words is
  'Từ do CHÍNH người học bấm tra khi đọc transcript. Đây mới là chương trình học thật — NGSL chỉ là cuốn từ điển được tra.';

-- Kiểm tra:
-- select count(*) from saved_words;
-- select term, definition_vi, due from saved_words order by created_at desc limit 10;
